Repository KiCad/kicad-symbols, pull requests merged in 2018-11, with the labels that each got.

#1102 Remove duplicate ATtiny1634 definition
  MCU_Microchip_ATtiny.dcm
  MCU_Microchip_ATtiny.lib
Labels: Enhancement, Pending review

#1084 Add AD8561ARZ comparator
  Comparator.dcm
  Comparator.lib
Labels: Addition, Pending review

#1083 Include AD8001ARZ amplifier
  Amplifier_Operational.dcm
  Amplifier_Operational.lib
Labels: Addition, Pending review

#1071 Add AD7606 series AD Converters.
  Analog_ADC.dcm
  Analog_ADC.lib
Labels: Addition

#603 add Würth 7499010121A RJ45 magjack
  Connector.dcm
  Connector.lib
Labels: Addition

#1100 Added TC1017.
  Regulator_Linear.dcm
  Regulator_Linear.lib
Labels: Addition

#1099 Added LPC122x MCUs.
  MCU_NXP_LPC.dcm
  MCU_NXP_LPC.lib
Labels: Addition

#1125 Added the 18 Pin SOIC version of the MCP2515
  Interface_CAN_LIN.dcm
  Interface_CAN_LIN.lib
Labels: Addition, Pending review

#1116 Add XP_POWER ISU02 series DC to DC converter symbol.
  Converter_DCDC.dcm
  Converter_DCDC.lib
Labels: Addition, Pending review

#1132 Updated data asheet link and foot print for LTS-6960HR
  Display_Character.dcm
  Display_Character.lib
Labels: Enhancement, Pending review

#1139 Add ATtiny202/402/212/412
  MCU_Microchip_ATtiny.dcm
  MCU_Microchip_ATtiny.lib
Labels: Addition, Pending review

#1143 Add ATtiny807/1607 and 417/817/1617/3217
  MCU_Microchip_ATtiny.dcm
  MCU_Microchip_ATtiny.lib
Labels: Addition, Pending review

#1144 Move CH376 from Memory_Controller to to Interface
  Interface.dcm
  Interface.lib
  Memory_Controller.dcm
  Memory_Controller.lib
  sym-lib-table
Labels: Enhancement

#1067 Added MUN3211DW Dual NPN BRT
  Transistor_BJT.dcm
  Transistor_BJT.lib
Labels: Addition

#1145 Add Artesyn ATA Series SMT DC to DC converter symbols.
  Converter_DCDC.dcm
  Converter_DCDC.lib
Labels: Addition

#1151 Fix "bibolar" typo.
  pspice.dcm
Labels: Enhancement

#1140 Converter_ACDC: Add isolation lines
  Converter_ACDC.lib
Labels: Enhancement, Pending review

#1156 Revert "Move CH376 from Memory_Controller to to Interface (#1144)"
  Interface.dcm
  Interface.lib
  Memory_Controller.dcm
  Memory_Controller.lib
  sym-lib-table
Labels: Enhancement, Pending review

#1159 4xxx_IEEE: Fix 4082 pin (solves #850)
  4xxx_IEEE.lib
Labels: Enhancement, Pending review

#728 Symbol for ESP-WROOM-02
  RF_Module.dcm
  RF_Module.lib
Labels: Addition

#1076 More audio jacks
  Connector.dcm
  Connector.lib
Labels: Addition

#1110 Add HDC2080
  Sensor_Humidity.dcm
  Sensor_Humidity.lib
Labels: Addition, Pending review

#1016 Initial version of the MAX6816
  Interface.dcm
  Interface.lib
Labels: Addition, Pending review

#1123 Add MAX11612/3
  Analog_ADC.dcm
  Analog_ADC.lib
Labels: Addition, Pending review

#1178 added 2 aliases for DRV5033
  Sensor_Magnetic.dcm
  Sensor_Magnetic.lib
Labels: Addition

#1179 corrected hall effect sensor out, from output to open collector
  Sensor_Magnetic.lib
Labels: Enhancement

#1177 Fix some footprints in Isolator.lib
  Isolator.dcm
  Isolator.lib
Labels: Enhancement, Re-push

#795 Tlc5971
  Driver_LED.dcm
  Driver_LED.lib
Labels: Addition

#1093 Add DRQFN packages for some ATmega MCUs
  MCU_Microchip_ATmega.dcm
  MCU_Microchip_ATmega.lib
Labels: Addition

#1038 Add LMH6551 fully differential opamp
  Amplifier_Operational.dcm
  Amplifier_Operational.lib
Labels: Addition

#986 Add LT3092
  Reference_Current.dcm
  Reference_Current.lib
Labels: Addition

#1188 Restore 3.3V HO8/15/25 symbols
  Sensor_Current.dcm
  Sensor_Current.lib
Labels: Addition

#1129 Added TPS54233 regulator
  Regulator_Switching.dcm
  Regulator_Switching.lib
Labels: Addition

#1183 Amplifier_Operational: Add ADA4841-1
  Amplifier_Operational.dcm
  Amplifier_Operational.lib
Labels: Addition
