Repository KiCad/kicad-symbols, pull requests merged in 2018-10, with the labels that each got.

#1029 Add symbol for XP Power JTE series dual output DC to DC converter.
  Converter_DCDC.dcm
  Converter_DCDC.lib
Labels: Addition, In review

#399 Add TWELITE SMD/DIP IEEE802.15.4 breakout module
  RF_ZigBee.dcm
  RF_ZigBee.lib
Labels: Addition, In review

#1032 Fix the VDD pin type for the PIC16F83 and PIC16F84. (from Bidirection…
  MCU_Microchip_PIC16.lib
Labels: Enhancement, Pending review

#1022 Add UFBGA-32 packages for ATtiny48/88
  MCU_Microchip_ATtiny.dcm
  MCU_Microchip_ATtiny.lib
Labels: Addition

#1024 Add QFN-28 packages for ATmega48
  MCU_Microchip_ATmega.dcm
  MCU_Microchip_ATmega.lib
Labels: Addition

#888 IS61C5128AL/AS IS64C5128AL/AS high speed CMOS SRAM 512KBx8 (take 2)
  Memory_RAM.dcm
  Memory_RAM.lib
Labels: Addition

#695 Adding SN74AUP1T34DCK
  Logic_LevelTranslator.dcm
  Logic_LevelTranslator.lib
Labels: Addition, Pending review

#880 Bus_ISA_8bit fix
  Connector.lib
Labels: Enhancement, Pending review

#1028 Add AD5691RxMRZ and AD5693RxMRZ I2C DACs
  Analog_DAC.dcm
  Analog_DAC.lib
Labels: Addition

#1036 Add missing aliases for ATxmega C3 and D3 MCUs
  MCU_Microchip_ATmega.dcm
  MCU_Microchip_ATmega.lib
Labels: Addition

#1023 Add DFN-8 packages for ATtiny4/5/9/10
  MCU_Microchip_ATtiny.dcm
  MCU_Microchip_ATtiny.lib
Labels: Enhancement

#1039 Add LMH6611 operational amplifier
  Amplifier_Operational.dcm
  Amplifier_Operational.lib
Labels: Addition, Pending review

#1044 Fix MCP1525-TO pinout
  Reference_Voltage.lib
Labels: Enhancement, Pending review

#1050 Add ATmega48/88/168PB
  MCU_Microchip_ATmega.dcm
  MCU_Microchip_ATmega.lib
Labels: Addition, Pending review

#572 Added symbol for the Infineon BTS50010-1TAD device
  Power_Management.dcm
  Power_Management.lib
Labels: Addition

#1020 Added AD6645 and AD6644 analog to digital converter.
  Analog_ADC.dcm
  Analog_ADC.lib
Labels: Addition

#1047 WCH CH330N USB-UART interface
  Interface_USB.dcm
  Interface_USB.lib
Labels: Addition

#1055 Add ATmega329/3290P
  MCU_Microchip_ATmega.dcm
  MCU_Microchip_ATmega.lib
Labels: Addition, Pending review

#1054 Add ATmega325/3250P
  MCU_Microchip_ATmega.dcm
  MCU_Microchip_ATmega.lib
Labels: Addition, Pending review

#1052 [Sensor Magnetic] Update datasheet link
  Sensor_Magnetic.dcm
Labels: Enhancement, Pending review

#1043 Add missing QFN packages for ATtiny2313A/4313
  MCU_Microchip_ATtiny.dcm
  MCU_Microchip_ATtiny.lib
Labels: Enhancement

#1056 Add ATxmega384C3
  MCU_Microchip_ATmega.dcm
  MCU_Microchip_ATmega.lib
Labels: Addition, Pending review

#1057 Add ATmega324PB
  MCU_Microchip_ATmega.dcm
  MCU_Microchip_ATmega.lib
Labels: Addition, Pending review

#594 Adding Texas Instruments PCM5102 symbol
  Audio.dcm
  Audio.lib
Labels: Addition

#995 add analog switch MAX14759
  Analog_Switch.dcm
  Analog_Switch.lib
Labels: Addition

#777 Lattice iCE40HX8K-BG121TR FPGA Symbol
  FPGA_Lattice.dcm
  FPGA_Lattice.lib
Labels: Addition

#993 Add generic symbol: LED_BARG
  Device.dcm
  Device.lib
Labels: Addition, Pending review

#985 Add pSemi GaN FET drivers
  Driver_FET.dcm
  Driver_FET.lib
Labels: Addition, Pending review

#839 Add AS1115
  Interface_Expansion.dcm
  Interface_Expansion.lib
Labels: Addition, Pending review

#996 add analog switch MAX14761
  Analog_Switch.dcm
  Analog_Switch.lib
Labels: Addition, Pending changes

#709 Adding VSC8541XMV-0x
  Interface_Ethernet.dcm
  Interface_Ethernet.lib
Labels: Addition

#915 Adding H5AN8G8NAFR-UHC
  Memory_RAM.dcm
  Memory_RAM.lib
Labels: Addition, Pending changes, Pending review

#796 Tmc2041 la
  Driver_Motor.dcm
  Driver_Motor.lib
Labels: Addition

#883 Adding ASP-134602-01
  Connector.dcm
  Connector.lib
Labels: Addition

#832 Power_Management: Add MAX8586
  Power_Management.dcm
  Power_Management.lib
Labels: Addition, Pending review

#1046 Adding MICRF112
  RF.dcm
  RF.lib
Labels: Addition

#1062 Add LTC1742/4/6/8 high speed ADCs
  Analog_ADC.dcm
  Analog_ADC.lib
Labels: Addition

#1042 Added symbols for AD849x Thermocouple Amp
  Sensor_Temperature.dcm
  Sensor_Temperature.lib
Labels: Addition

#960 Added DAC7750IR
  Analog_DAC.dcm
  Analog_DAC.lib
Labels: Addition, Pending review

#1077 Add symbol for CSD16301Q2
  Transistor_FET.dcm
  Transistor_FET.lib
Labels: Addition

#924 Adding Si7336ADP
  Transistor_FET.dcm
  Transistor_FET.lib
Labels: Addition

#1080 Added INA260
  Sensor.dcm
  Sensor.lib
Labels: Addition, Re-push

#956 Delete old files
  TODO.md
  rename.json
  rename_stagger.json
  replace.json
  replace_add_ep-size.json
Labels: Enhancement, Pending review

#1007 Added FDMC8032L mosfet
  Transistor_FET.dcm
  Transistor_FET.lib
Labels: Addition, Pending review

#918 Security: Create new library and add ATECC608A crypto co-processor
  Security.dcm
  Security.lib
  sym-lib-table
Labels: Addition

#990 Add TPS703x and TPS704x
  Regulator_Linear.dcm
  Regulator_Linear.lib
Labels: Addition

#1088 Add SN74AHCT123ANE4
  74xx.dcm
  74xx.lib
Labels: Addition

#1082 Add LT1019 precision voltage reference
  Reference_Voltage.dcm
  Reference_Voltage.lib
Labels: Addition, Pending review

#1101 ICE40HX8K-BG121: split out GNDPLL0/1
  FPGA_Lattice.lib
Labels: Enhancement

#935 Interface_Ethernet Fix S3.6
  Interface_Ethernet.lib
Labels: Enhancement
