Repository KiCad/kicad-symbols, pull requests merged in 2018-12, with the labels that each got.

#724 Add Symbol for ESP32-WROOM-32 RF module
  RF_Module.dcm
  RF_Module.lib
Labels: Addition

#750 MCU_Microchip_PIC16: Add PIC16F18325 QFN variants
  MCU_Microchip_PIC16.dcm
  MCU_Microchip_PIC16.lib
Labels: Addition, Pending footprint

#1142 Add ATtiny406/806/1606 and 416/816/1616/3216
  MCU_Microchip_ATtiny.dcm
  MCU_Microchip_ATtiny.lib
Labels: Addition, Pending footprint

#1220 Reference_Voltage: Fix RefDes in multiple devices
  Reference_Voltage.lib
Labels: Enhancement, Pending reviewer

#1135 Power_Supervisor: Add MCP39F521
  Power_Supervisor.dcm
  Power_Supervisor.lib
Labels: Addition

#1160 Add 7705
  Regulator_SwitchedCapacitor.dcm
  Regulator_SwitchedCapacitor.lib
Labels: Addition

#1034 Visible pin numbers on R networks
  Device.lib
Labels: Enhancement

#1227 fix #977
  Regulator_Linear.dcm
  Regulator_Linear.lib
Labels: Enhancement

#824 Add LMV727x low power comparators
  Comparator.dcm
  Comparator.lib
Labels: Addition

#1247 Valve: Update to latest file format
  Valve.dcm
  Valve.lib
Labels: Enhancement, Pending reviewer

#940 Add LM675
  Amplifier_Operational.dcm
  Amplifier_Operational.lib
Labels: Addition

#1257 Triac and IGBT: Update to latest file version
  Transistor_IGBT.lib
  Triac_Thyristor.lib
Labels: Enhancement, Pending reviewer

#1233 add LMH6702MA+LMH6609MA as variant of existing symbol
  Amplifier_Operational.dcm
  Amplifier_Operational.lib
Labels: Addition

#1256 Regulator_Linear: Fix FPFilters
  Regulator_Linear.lib
Labels: Enhancement

#1232 LVCMOS 1:8 clock-buffer IDT 5PB1108PGG in TSSOP-16
  Interface.dcm
  Interface.lib
Labels: Addition

#1228 #957 HLCP-J100 footprint filter
  LED.lib
Labels: Enhancement

#1246 add ADA4898-2 dual opamp in SOIC-8-1EP
  Amplifier_Operational.dcm
  Amplifier_Operational.lib
Labels: Addition, Pending reviewer

#1245 add LT1790-series voltage references (TSOT-23-6)
  Reference_Voltage.dcm
  Reference_Voltage.lib
Labels: Addition, Pending reviewer

#1244 Add MIC29152/302/502/752/153/303/503 regulators
  Regulator_Linear.dcm
  Regulator_Linear.lib
Labels: Addition, Pending reviewer

#1131 Add Fiducial as schematic symbol
  Mechanical.dcm
  Mechanical.lib
Labels: Addition, Pending reviewer

#885 Adding MAX3218
  Interface_UART.dcm
  Interface_UART.lib
Labels: Addition, Pending reviewer

#874 Sensor_Optical: add NOA1305 ambient sensor
  Sensor_Optical.dcm
  Sensor_Optical.lib
Labels: Addition, Pending reviewer

#865 adds symbols for AP6502 and AP6503
  Regulator_Switching.dcm
  Regulator_Switching.lib
Labels: Addition, Pending reviewer

#1261 Add TPS5420D.
  Regulator_Switching.dcm
  Regulator_Switching.lib
Labels: Addition, Pending reviewer

#1255 Add P-MOS - Vishay SiS415DNT
  Transistor_FET.dcm
  Transistor_FET.lib
Labels: Addition

#1171 add LT3015Q
  Regulator_Linear.dcm
  Regulator_Linear.lib
Labels: Addition, Pending reviewer

#1235 Add ADA4898-1 in SOIC-8-1EP
  Amplifier_Operational.dcm
  Amplifier_Operational.lib
Labels: Addition

#1169 add lt1963eq (alias lt1963aeq)
  Regulator_Linear.dcm
  Regulator_Linear.lib
Labels: Addition

#1268 LT3010-5/ADJ: fixes NC pins (#1259) and other fixes
  Regulator_Linear.dcm
  Regulator_Linear.lib
Labels: Enhancement, Pending reviewer

#1222 Add ATmega406
  MCU_Microchip_ATmega.dcm
  MCU_Microchip_ATmega.lib
Labels: Addition

#1276 Correct footprint assignment for AD7722
  Analog_ADC.lib
Labels: Enhancement, Pending reviewer

#1014 Add LMZM23600 Power Module
  Regulator_Switching.dcm
  Regulator_Switching.lib
Labels: Addition

#1285 Interface_Telecom: Update datasheet of FX614
  Interface_Telecom.dcm
Labels: Enhancement

#1262 Add TPS7A7200RGW.
  Regulator_Switching.dcm
  Regulator_Switching.lib
Labels: Addition, Pending reviewer

#1260 Add LM22676MR.
  Regulator_Switching.dcm
  Regulator_Switching.lib
Labels: Addition, Pending reviewer

#1085 Add digital isolator HCPL-9000
  Isolator.dcm
  Isolator.lib
Labels: Addition, Pending reviewer

#1293 Fixed type of 4023 and 4025 output pins from 'open collector' to 'output'
  4xxx.lib
Labels: Enhancement

#1147 converter-acdc: add HLK module series
  Converter_ACDC.dcm
  Converter_ACDC.lib
Labels: Addition

#1103 new symbol: Conn_Coaxial_x2_Isolated
  Connector.dcm
  Connector.lib
Labels: Addition

#1263 Added TSV524xIQ4T
  Amplifier_Operational.dcm
  Amplifier_Operational.lib
Labels: Addition

#1189 Add ATmega3209/4809
  MCU_Microchip_ATmega.dcm
  MCU_Microchip_ATmega.lib
Labels: Addition, Pending footprint

#721 XC6220B331MR - 1A LDO Voltage Regulator
  Regulator_Linear.dcm
  Regulator_Linear.lib
Labels: Addition

#1280 add MC12093D
  RF.dcm
  RF.lib
Labels: Addition

#1282 add 74AHC1G4210
  74xGxx.dcm
  74xGxx.lib
Labels: Addition

#1292 Add 4075: triple OR 3 inputs
  4xxx.dcm
  4xxx.lib
Labels: Addition

#1295 Isolator: Add ISO1541
  Isolator.dcm
  Isolator.lib
Labels: Addition

#1124 Add LMP8640
  Amplifier_Current.dcm
  Amplifier_Current.lib
Labels: Addition

#1283 add MC12080
  RF.dcm
  RF.lib
Labels: Addition

#1320 Fixing RTS/DSR pin directionality on FT230/FT231 devices.
  Interface_USB.lib
Labels: Bug

#1308 Fix footprint for TPA5050
  Audio.lib
Labels: Bug

#1321 Fix footprint assignement for attiny qfn-20 versions
  MCU_Microchip_ATtiny.lib
Labels: Bug, Pending reviewer

#1324 Fix footprint assignment QFN-16-1ep Interface USB
  Interface_USB.lib
Labels: Bug, Pending reviewer

#1323 Fix fp assignment for XPT2046QF (corrected ep size)
  Driver_Display.lib
Labels: Bug, Pending reviewer

#1318 Fix footprint assignment for SX127x
  RF.dcm
  RF.lib
Labels: Bug, Pending footprint

#1306 add OPA188 in SOT-23 as new alias
  Amplifier_Operational.dcm
  Amplifier_Operational.lib
Labels: Addition

#1310 add OPA188 in SOIC-8
  Amplifier_Operational.dcm
  Amplifier_Operational.lib
Labels: Addition

#1097 Add ublox max series
  RF_GPS.dcm
  RF_GPS.lib
Labels: Addition

#1304 Correct qfn-16-1p footprint assignment for NXP MCUs
  MCU_NXP_Kinetis.lib
Labels: Bug, Pending reviewer

#1303 Fix qfn-16-1ep assignments in driver motor
  Driver_Motor.lib
Labels: Bug, Pending reviewer

#1205 Add MAX40200
  Analog_Switch.dcm
  Analog_Switch.lib
Labels: Addition

#1329 Added TPS7A7001DDA.
  Regulator_Linear.dcm
  Regulator_Linear.lib
Labels: Addition

#1328 TPS7A7200RGW should be in Regulator_Linear.
  Regulator_Linear.dcm
  Regulator_Linear.lib
  Regulator_Switching.dcm
  Regulator_Switching.lib
Labels: Bug

#1270 Added ATMega-0-Series Devices
  MCU_Microchip_ATmega.dcm
  MCU_Microchip_ATmega.lib
Labels: Addition, Pending reviewer

#657 Symbol for PAM2306
  Regulator_Switching.dcm
  Regulator_Switching.lib
Labels: Addition, Pending reviewer

#647 Esp psram32
  Memory_RAM.dcm
  Memory_RAM.lib
Labels: Addition, Enhancement, Pending reviewer

#766 Add Inolux IN-PI554FCH and IN-PI556FCH RGB addressable LEDs
  LED.dcm
  LED.lib
Labels: Addition, Pending reviewer

#771 Fixed documentations URLs and pins type of the CP2102, CP2104, CP2112…
  Interface_USB.dcm
  Interface_USB.lib
Labels: Enhancement, Pending reviewer

#789 Add ADS70xx ADCs in VSSOP8 package
  Analog_ADC.dcm
  Analog_ADC.lib
Labels: Addition

#1158 ublox Sara U2xx Symbol
  RF.dcm
  RF.lib
Labels: Addition

#1341 Correct fp assignment for MCU_NXP_SO8 (qfn 24 5x5)
  MCU_NXP_S08.lib
Labels: Bug, Pending reviewer

#1348 Correct fp for FE310-G000 (qfn-48)
  MCU_SiFive.lib
Labels: Bug, Pending reviewer

#1347 Fix fp assignement for nordic mcus (qfn-48)
  MCU_Nordic.lib
Labels: Bug, Pending reviewer

#1353 Use nominal EP size for cypress qfn-56 7x7
  MCU_Cypress.lib
Labels: Bug, Pending reviewer

#787 Adding Lattice XP2-5 in TQFP-144
  FPGA_Lattice.dcm
  FPGA_Lattice.lib
Labels: Addition, Pending reviewer

#1096 Add ublox lea series
  RF_GPS.dcm
  RF_GPS.lib
Labels: Addition

#1344 Added 74AHC2G00 and 74AHCT2G00 to 74xGxx library.
  74xGxx.dcm
  74xGxx.lib
Labels: Addition

#1316 Fix for #1273
  Interface.dcm
  Interface.lib
Labels: Addition

#1356 Update RF_GPS
  RF_GPS.lib
Labels: Enhancement

#1098 Add ublox NEO M8 series
  RF_GPS.dcm
  RF_GPS.lib
Labels: Addition

#1345 Fix fp assignement for PIC18 MCUs (qfn-44)
  MCU_Microchip_PIC18.dcm
  MCU_Microchip_PIC18.lib
Labels: Bug, Pending reviewer

#1095 Add DIN rail adapter
  Mechanical.dcm
  Mechanical.lib
Labels: Addition

#1346 add LT3015xQ-2.5/3/3.3/5/12/15 in TO-263-5
  Regulator_Linear.dcm
  Regulator_Linear.lib
Labels: Addition
