Repository KiCad/kicad-symbols, pull requests merged in 2019-04, with the labels that each got.

#1675 Raspberry Pi Compute Modue 3 Plus
  MCU_Module.dcm
  MCU_Module.lib
Labels: Addition

#1586 Add HMC7992.
  RF_Switch.dcm
  RF_Switch.lib
Labels: Addition

#1582 Add 93LCxxAxxOT.
  Memory_EEPROM.dcm
  Memory_EEPROM.lib
Labels: Addition

#1699 Fix LTC2875
  Interface_CAN_LIN.dcm
  Interface_CAN_LIN.lib
Labels: Bug, Pending reviewer

#1705 Add AS179-92LF
  RF_Switch.dcm
  RF_Switch.lib
Labels: Addition, Pending reviewer

#1667 Add ltm8063
  Regulator_Switching.dcm
  Regulator_Switching.lib
Labels: Addition

#1574 Oscillator: Add Abracon ASDMB device family
  Oscillator.dcm
  Oscillator.lib
Labels: Addition, Pending footprint

#1664 Adds A3214ELHLT-T Hall effect sensor to Sensor_Magnetic
  Sensor_Magnetic.dcm
  Sensor_Magnetic.lib
Labels: Addition

#1701 Add Si446x
  RF.dcm
  RF.lib
Labels: Addition

#1702 Amplifier_Audio: add MAX9715
  Amplifier_Audio.dcm
  Amplifier_Audio.lib
Labels: Addition, Pending reviewer

#1689 Logic_LevelTranslator: Add SN74AVC4T245PW
  Logic_LevelTranslator.dcm
  Logic_LevelTranslator.lib
Labels: Addition

#1608 WE 750343373
  Transformer.dcm
  Transformer.lib
Labels: Addition, Pending footprint

#1706 Add TPS2419
  Power_Management.dcm
  Power_Management.lib
Labels: Addition

#1681 Driver_LED: Add MPQ2483
  Driver_LED.dcm
  Driver_LED.lib
Labels: Addition

#1710 Added LTC7138
  Regulator_Switching.dcm
  Regulator_Switching.lib
Labels: Addition

#1713 Driver_LED: MPQ2483DQ: Fix thermal pad assignment
  Driver_LED.lib
Labels: Bug

#1715 Regulator_SwitchedCapacitor: add TPS60151DRV
  Regulator_SwitchedCapacitor.dcm
  Regulator_SwitchedCapacitor.lib
Labels: Addition

#875 Added PIC18F4420-xP and PIC18F4520-xP
  MCU_Microchip_PIC18.dcm
  MCU_Microchip_PIC18.lib
Labels: Addition

#1679 Add G6SK-2 symbol
  Relay.dcm
  Relay.lib
Labels: Addition

#1688 Added SN6505ADBVR SN6505BDBVR under regulators_switching
  Power_Management.dcm
  Power_Management.lib
Labels: Addition

#1682 NLSV2T244
  Logic_LevelTranslator.dcm
  Logic_LevelTranslator.lib
Labels: Addition

#1676 Audio: Add CS4270 Codec
  Audio.dcm
  Audio.lib
Labels: Addition

#1726 Fix CY7C65215
  Interface_USB.lib
Labels: Bug, Pending reviewer

#1610 Add Texas TPS568215
  Regulator_Switching.dcm
  Regulator_Switching.lib
Labels: Addition

#1687 Rv 1805
  Timer_RTC.dcm
  Timer_RTC.lib
Labels: Addition

#1633 added symbols for BD48xxx/BD49xxx series
  Power_Management.dcm
  Power_Management.lib
Labels: Addition, Pending reviewer

#1006 Added MCP14A030x
  Driver_FET.dcm
  Driver_FET.lib
Labels: Addition, Pending changes

#1652 SN65HVD1050
  Interface_CAN_LIN.dcm
  Interface_CAN_LIN.lib
Labels: Addition

#1653 Added MCP2542FD
  Interface_CAN_LIN.dcm
  Interface_CAN_LIN.lib
Labels: Addition

#1315 add HMC394 counter/prescaler in QFN-24
  RF.dcm
  RF.lib
Labels: Addition

#1690 Added AS72651
  Sensor_Optical.dcm
  Sensor_Optical.lib
Labels: Addition

#1707 Added the NXP PCF8525T I2C Real Time Clock
  Timer_RTC.dcm
  Timer_RTC.lib
Labels: Addition, Re-push

#1238 Add THS3491 op-amp in SOIC-8-1EP
  Amplifier_Operational.dcm
  Amplifier_Operational.lib
Labels: Addition

#1730 Interface_UART: Add ADM2682E and ADM2687E
  Interface_UART.dcm
  Interface_UART.lib
Labels: Addition

#1236 Add support for USR USR-C322 3Mbps UART-WIFI Module.
  RF_WiFi.dcm
  RF_WiFi.lib
Labels: Addition

#1738 The 74HC244 is a tri-state buffer, but the symbol have simple output.
  74xx.lib
Labels: Bug

#1742 THAT2181: Description typo
  Amplifier_Audio.dcm
Labels: Bug

#696 Adding SiFive FU540-C000 MCU
  MCU_SiFive.dcm
  MCU_SiFive.lib
Labels: Addition

#1732 PCF8523TK
  Timer_RTC.dcm
  Timer_RTC.lib
Labels: Addition

#1752 Datasheet MCP9700
  Sensor_Temperature.dcm
Labels: Enhancement

#1758 Update datasheet of SHT1x
  Sensor.dcm
  Sensor.lib
Labels: Bug

#1759 fix swapped pins 12 & 13 on DS1267_SOIC symbol
  Potentiometer_Digital.lib
Labels: Bug

#1755 add ONET1191PRGT 11.3Gbps limiting amplifier, QFN-16
  Interface.dcm
  Interface.lib
Labels: Addition

#1756 PCF8523TS Addition of TSSOP-14 Symbol
  Timer_RTC.dcm
  Timer_RTC.lib
Labels: Addition

#1736 added TPS3808
  Power_Supervisor.dcm
  Power_Supervisor.lib
Labels: Addition

#1737 added TLV733PDBV
  Regulator_Linear.dcm
  Regulator_Linear.lib
Labels: Addition

#1743 added ExpressCard connector
  Connector.dcm
  Connector.lib
Labels: Addition

#1761 Add CPC1002N
  Relay_SolidState.dcm
  Relay_SolidState.lib
Labels: Addition

#1760 Add LTV-247
  Isolator.dcm
  Isolator.lib
Labels: Addition

#1762 Correct footprint of TCA9534 from SO-20 to SO-16
  Interface_Expansion.dcm
  Interface_Expansion.lib
Labels: Bug

#1766 Add alias of TPS7A90 to TPS7A91
  Regulator_Linear.dcm
  Regulator_Linear.lib
Labels: Addition

#1765 Fix pinout TXB0108DQSR
  Logic_LevelTranslator.lib
Labels: Bug

#1767 Add LT3514 QFN-28
  Regulator_Switching.dcm
  Regulator_Switching.lib
Labels: Addition

#1734 Regulator_Linear: Add SOT23 variants of MCP1754S
  Regulator_Linear.dcm
  Regulator_Linear.lib
Labels: Addition, Enhancement, Re-push

#1750 Add LT3580
  Regulator_Switching.dcm
  Regulator_Switching.lib
Labels: Addition

#1746 Vishay H11AA1 Optocoupler
  Isolator.dcm
  Isolator.lib
Labels: Addition

#1745 added TPS2500/2501
  Interface_USB.dcm
  Interface_USB.lib
Labels: Addition

#1739 add TXS0102DCT, TXS0102DCU, TXS0102DQE, TXS0102YZP
  Logic_LevelTranslator.dcm
  Logic_LevelTranslator.lib
Labels: Addition

#1763 Add TCA9554
  Interface_Expansion.dcm
  Interface_Expansion.lib
Labels: Addition

#1768 Add AM26LV32
  Interface.dcm
  Interface.lib
Labels: Addition

#1696 Adding MXM3.0 connector
  Connector.dcm
  Connector.lib
Labels: Addition

#1518 Adding ICE40HX1K-TQ144
  FPGA_Lattice.dcm
  FPGA_Lattice.lib
Labels: Addition

#1774 Fix mirrored hysteresis symbol, datasheet link for 74LVC1G14, 74LVC3G14, 74LVC3G14
  74xGxx.dcm
  74xGxx.lib
Labels: Enhancement

#1327 add SFP/SFP+ connector
  Interface_Optical.dcm
  Interface_Optical.lib
Labels: Addition

#1593 add generic SW_Push_DPDT
  Switch.dcm
  Switch.lib
Labels: Addition

#1770 added symbol - Memory_RAM/IDT7006PF dual 16k x 8 dual port ram
  Memory_RAM.dcm
  Memory_RAM.lib
Labels: Addition

#1500 Add shield pin to Wuerth_7499010121A
  Connector.lib
Labels: Enhancement

#1773 Add missing hysteresis symbol on 74LS14 (and 74HC14 alias)
  74xx.lib
Labels: Enhancement

#1728 BQ25570: Nano power boost charger and buck converter
  Battery_Management.dcm
  Battery_Management.lib
Labels: Addition

#1695 muRata OKI-78SR serie
  Converter_DCDC.dcm
  Converter_DCDC.lib
Labels: Addition, Re-push

#1783 Swap pins of BPW21
  Sensor_Optical.lib
Labels: Bug

#1775 Driver_LED: Add DIO5661x
  Driver_LED.dcm
  Driver_LED.lib
Labels: Addition

#1779 fixing 40374, and add 74AHC/AHCT244 alias
  4xxx_IEEE.dcm
  4xxx_IEEE.lib
  74xx.dcm
  74xx.lib
Labels: Addition, Enhancement

#1785 Sensor_Temperature: Add PCT2075
  Sensor_Temperature.dcm
  Sensor_Temperature.lib
Labels: Addition

#1784 Driver_LED: Add TLC59108IPWR
  Driver_LED.dcm
  Driver_LED.lib
Labels: Addition

#1793 Corrections
  Regulator_Controller.lib
Labels: Enhancement, Pending reviewer
