Repository KiCad/kicad-symbols, pull requests merged in 2019-02, with the labels that each got.

#1455 add MSW(A)-2 RF switches
  RF_Switch.dcm
  RF_Switch.lib
Labels: Addition

#1194 NXP SA636
  RF_AM_FM.dcm
  RF_AM_FM.lib
Labels: Addition

#1407 Add NB3N551MN.
  Interface.dcm
  Interface.lib
Labels: Addition

#1484 add "Heatsink:*" fp-filter to both heatsink-symbols.
  Mechanical.dcm
  Mechanical.lib
Labels: Enhancement

#1479 Update fp assignement for TPS7A7200RGW
  Regulator_Linear.lib
Labels: Enhancement, Pending footprint

#1480 Fix footpritn assignment for ADA4898-x
  Amplifier_Operational.dcm
  Amplifier_Operational.lib
Labels: Bug, Pending footprint

#1482 Fix footprint assignment for A4950E
  Driver_Motor.lib
Labels: Bug, Pending footprint

#1483 Fix SOIC-8 EP footprint assignments in switching regulator library
  Regulator_Switching.lib
Labels: Bug, Pending footprint

#1489 Fix NC pin positions
  Audio.lib
Labels: Enhancement, Pending reviewer

#1487 Fix footprint assignment for PM8834M
  Driver_FET.lib
Labels: Bug, Pending reviewer

#1488 Fix footprint assignement for LM25085MY and LM3407MY
  Regulator_Switching.lib
Labels: Bug, Pending reviewer

#1481 Fix footprint assignment for HIP2100
  Driver_FET.lib
Labels: Bug, Pending footprint, ReadyForReview

#1436 Add LMH7324
  Comparator.dcm
  Comparator.lib
Labels: Addition

#1492 Add Geiger-Müller symbol
  Valve.dcm
  Valve.lib
Labels: Addition

#1197 Analog ADC: create ADS8684 and ADS8688
  Analog_ADC.dcm
  Analog_ADC.lib
Labels: Addition

#1340 Addition Of Traco DC-DC Converters
  Converter_DCDC.dcm
  Converter_DCDC.lib
Labels: Addition

#1184 Add D52M
  RF_Module.dcm
  RF_Module.lib
Labels: Addition

#1502 Move Geiger-Muller from Valve to Sensors
  Sensor.dcm
  Sensor.lib
  Valve.dcm
  Valve.lib
Labels: Enhancement, Pending reviewer

#914 Adding IS25WP256D-xM
  Memory_Flash.dcm
  Memory_Flash.lib
Labels: Addition

#1086 Add XP Power DC converters IA1205S and IH1205S and ITX1205S
  Converter_DCDC.dcm
  Converter_DCDC.lib
Labels: Addition

#1130 Added SA15-11SRWA 7 segment display
  Display_Character.dcm
  Display_Character.lib
Labels: Addition

#1507 Make ATxmega PDI_DATA pins Bidirectional
  MCU_Microchip_ATmega.lib
Labels: Enhancement

#1473 Add new simulation symbol lib
  Simulation_SPICE.dcm
  Simulation_SPICE.lib
  sym-lib-table
Labels: Addition, Pending changes

#1472 Add VCAP1 pin to ADS1298 and update symbol
  Analog_ADC.dcm
  Analog_ADC.lib
Labels: Bug, Enhancement, Re-push

#1385 Fix Memory_UniqueID
  Memory_UniqueID.dcm
  Memory_UniqueID.lib
Labels: Enhancement

#1048 Added AH1806 family
  Sensor_Magnetic.dcm
  Sensor_Magnetic.lib
Labels: Addition, Pending footprint

#887 Adding CAT24C128 (alias for 24LC16)
  Memory_EEPROM.dcm
  Memory_EEPROM.lib
Labels: Addition

#1078 Add NXP i.MX6 CPUs
  CPU_NXP_IMX.dcm
  CPU_NXP_IMX.lib
  sym-lib-table
Labels: Addition

#1505 Pressure sensor MS5607
  Sensor_Pressure.dcm
  Sensor_Pressure.lib
Labels: Addition

#1196 Connector: create Mini-PCIe
  Connector.dcm
  Connector.lib
Labels: Addition

#1465 Added haptic driver from TI - DRV2510-Q1.
  Driver_Haptic.dcm
  Driver_Haptic.lib
  sym-lib-table
Labels: Addition, Librarian

#1190 Analog_Switch: Add ADG1414
  Analog_Switch.dcm
  Analog_Switch.lib
Labels: Addition

#1467 Added new foot print for MPL115A1
  Sensor_Pressure.lib
Labels: Bug, Pending footprint

#1466 Added STP08CP05 and STP16CP05
  Driver_LED.dcm
  Driver_LED.lib
Labels: Addition

#605 add Mini-Circuits LFCN/BFCN/HFCN passive 1206 filters
  Filter.lib
  RF_Filter.dcm
  RF_Filter.lib
  sym-lib-table
Labels: Addition

#1508 Fix FP assignment TI PWQFN motor drivers
  Driver_Motor.lib
Labels: Enhancement, Pending footprint, Pending reviewer

#1509 Fix footprint for BQ25601
  Battery_Management.lib
Labels: Enhancement, Pending footprint, Pending reviewer

#1294 Sensor_Optical: Add APDS-9306 and APDS-9306-065
  Sensor_Optical.dcm
  Sensor_Optical.lib
Labels: Addition

#1498 Added Recom RPM-family of DC/DC converters to symbol lib (1A, 2A, 3A and 6A, non-isolating)
  Converter_DCDC.dcm
  Converter_DCDC.lib
Labels: Addition

#1469 Added MCP3202
  Analog_ADC.dcm
  Analog_ADC.lib
Labels: Addition

#1430 add onion omega2+
  MCU_Module.dcm
  MCU_Module.lib
Labels: Addition

#1496 Add Circuit Breakers
  Device.dcm
  Device.lib
Labels: Addition

#1506 Fix footprint assignment for LTC3553
  Battery_Management.lib
Labels: Bug, Pending footprint, Pending reviewer

#1494 Fix footprint (MSOP-10 EP) assignment for A4952_LY
  Driver_Motor.lib
Labels: Bug, Pending footprint, Pending reviewer

#1499 Fix footprint assignemnt for SOP-4 isolators
  Isolator.dcm
  Isolator.lib
Labels: Enhancement, Pending reviewer

#1468 Adding data sheet and variants of the MC3306D and other power supervi…
  Power_Supervisor.dcm
  Power_Supervisor.lib
Labels: Addition, Enhancement, Question

#1045 Texas Instruments PGA112/PGA113 programmable gain amplifier footprint
  Analog.dcm
  Analog.lib
Labels: Addition

#1527 Fix SANYOU SRD pin numbers
  Relay.lib
Labels: Bug, Pending reviewer

#1068 Added LED_Dual_CACA to Device.lib
  Device.dcm
  Device.lib
Labels: Addition

#1529 add OPA842, OPA843 and OPA846 as aliases
  Amplifier_Operational.dcm
  Amplifier_Operational.lib
Labels: Addition

#1525 Move rf-filters to RF_Filter
  RF.dcm
  RF.lib
  RF_Filter.dcm
  RF_Filter.lib
Labels: Enhancement, Pending reviewer

#1081 Added LP2951 8 pin variants
  Regulator_Linear.dcm
  Regulator_Linear.lib
Labels: Addition, Re-push

#1504 MCU Module: Create VisionSOM-RT
  MCU_Module.dcm
  MCU_Module.lib
Labels: Addition, Pending reviewer

#1535 Added SiA449DJ P-FET
  Transistor_FET.dcm
  Transistor_FET.lib
Labels: Addition

#1536 Add TLV6001DCK op-amp
  Amplifier_Operational.dcm
  Amplifier_Operational.lib
Labels: Addition

#1478 Added SIM28ML
  RF_GPS.dcm
  RF_GPS.lib
Labels: Addition

#1516 Fixed pinout of the LTC2508-32.
  Analog_ADC.dcm
  Analog_ADC.lib
Labels: Bug

#1510 Improve SPICE library symbol descriptions
  Simulation_SPICE.dcm
Labels: Enhancement

#1503 Add ATSAME54N19A-A
  MCU_Microchip_SAME.dcm
  MCU_Microchip_SAME.lib
Labels: Addition

#1501 Add APA102
  LED.dcm
  LED.lib
Labels: Addition, Pending footprint

#1490 Remove part name from description in power ports
  power.dcm
  power.lib
Labels: Addition, Enhancement

#1229 Add Symbols for TJA1043T and TJA1043TK CAN FD Transceivers
  Interface_CAN_LIN.dcm
  Interface_CAN_LIN.lib
Labels: Addition

#718 Add symbols for Microchip SAMD[09|10|11] devices
  MCU_Microchip_SAMD.dcm
  MCU_Microchip_SAMD.lib
  sym-lib-table
Labels: Addition

#1534 Added BQ500100DCK current shunt amplifier
  Amplifier_Current.dcm
  Amplifier_Current.lib
Labels: Addition

#1555 Prevent unit interchangeability in generic opamps
  Device.lib
Labels: Bug

#1538 Added TI TCA980x I2C buffer / translators
  Interface.dcm
  Interface.lib
Labels: Addition

#1182 Interface_USB: Add CH340T USB - TTL converter
  Interface_USB.dcm
  Interface_USB.lib
Labels: Addition

#1474 Symbol for Quectel Bc66
  RF_GSM.dcm
  RF_GSM.lib
Labels: Addition

#1441 Fix KLC errors on Memory_RAM:628128
  Memory_RAM.dcm
  Memory_RAM.lib
Labels: Enhancement

#1550 Replace sensor/Geiger-Muller with sensor/Nuclear-Radiation_Detector
  Sensor.dcm
  Sensor.lib
Labels: Enhancement, Pending reviewer

#1549 Added bq25895
  Battery_Management.dcm
  Battery_Management.lib
Labels: Addition

#1559 Add TJA1145 CAN Transceivers
  Interface_CAN_LIN.dcm
  Interface_CAN_LIN.lib
Labels: Addition

#1567 fix LTC6957-1: LVPECL outputs are open emitters
  Interface.lib
Labels: Addition, Bug

#1562 convert linear.com links to analog.com
  Amplifier_Current.dcm
  Amplifier_Instrumentation.dcm
  Amplifier_Operational.dcm
  Analog.dcm
  Analog_ADC.dcm
  Analog_DAC.dcm
  Battery_Management.dcm
  Comparator.dcm
  Driver_FET.dcm
  Driver_LED.dcm
  Interface.dcm
  Interface_CAN_LIN.dcm
  Interface_UART.dcm
  Power_Management.dcm
  RF_Mixer.dcm
  Reference_Voltage.dcm
  Regulator_Controller.dcm
  Regulator_Linear.dcm
  Regulator_SwitchedCapacitor.dcm
  Regulator_Switching.dcm
  Sensor.dcm
  Sensor_Temperature.dcm
Labels: Enhancement

#1395 Re-add lost Infineon (IR) symbols
  Amplifier_Audio.dcm
  Amplifier_Audio.lib
  Driver_FET.dcm
  Driver_FET.lib
  Power_Management.dcm
  Power_Management.lib
  Regulator_Controller.dcm
  Regulator_Controller.lib
  Sensor_Current.dcm
  Sensor_Current.lib
Labels: Addition, Enhancement

#1545 Added KX?22 series of accelerometers
  Sensor_Motion.dcm
  Sensor_Motion.lib
Labels: Addition, Pending reviewer

#1578 Switch dual fix
  Switch.lib
Labels: Bug

#1475 add AD8475 differential amplifier
  Amplifier_Difference.dcm
  Amplifier_Difference.lib
Labels: Addition, Pending footprint

#1573 Isolator: Add ADuM26xN devices
  Isolator.dcm
  Isolator.lib
Labels: Addition

#1577 Transistor_FET: Add a couple of TI CSD transistors
  Transistor_FET.dcm
  Transistor_FET.lib
Labels: Addition

#1575 Diode: Add BAV199DW
  Diode.dcm
  Diode.lib
Labels: Addition

#1060 Fixed pinout of USB6B1
  Power_Protection.lib
Labels: Bug, Enhancement

#1580 Add/correct FP filters for jumper symbols
  Device.lib
  Jumper.lib
Labels: Bug
