Repository KiCad/kicad-symbols, pull requests merged in 2019-09, with the labels that each got.

#1134 Add RAYEX ELECTRONICS L90 Series 30A Relay
  Relay.dcm
  Relay.lib
Labels: Addition, Ready for review

#2112 Isolator: Fix ADN4651 and ADN4652 order in the files
  Isolator.dcm
  Isolator.lib
Labels: Enhancement

#2124 fix minicircuits ww2 library links
  Oscillator.dcm
  RF.dcm
  RF_Switch.dcm
  Transformer.dcm
Labels: Enhancement

#1049 remove trademarked USB superspeed logos from USB3 connectors
  Connector.lib
Labels: Enhancement, Help wanted, Pending reviewer

#2090 add EMI filter Schaffner FN406
  Filter.dcm
  Filter.lib
Labels: Addition, Pending footprint, Pending reviewer

#2126 Fix PCA* I²C clock pin types
  Interface_Expansion.lib
Labels: Enhancement, Pending reviewer

#2120 Add PCA9537
  Interface_Expansion.dcm
  Interface_Expansion.lib
Labels: Addition

#2008 add MAAVSS0004 voltage variable attenuator
  RF.dcm
  RF.lib
Labels: Addition, Pending reviewer

#2110 Isolator: Fix names and descriptions for HCPL-061/063/261/263
  Isolator.dcm
  Isolator.lib
Labels: Enhancement, Pending reviewer

#2113 Isolator: Add 6N137 and related optocouplers
  Isolator.dcm
  Isolator.lib
Labels: Addition

#2100 Add HT75xx-1 voltage regulators
  Regulator_Linear.dcm
  Regulator_Linear.lib
Labels: Addition

#1976 Commonalize Transistor_FET
  Transistor_FET.lib
Labels: Enhancement, Pending reviewer

#2046 add Si41612DY MOSFET as alias
  Transistor_FET.dcm
  Transistor_FET.lib
Labels: Addition, Pending reviewer

#2066 add BSP89 as alias and fix symbol of BSP129
  Transistor_FET.dcm
  Transistor_FET.lib
Labels: Addition, Pending reviewer

#2138 Move MCP6561 to Comparator.lib
  Amplifier_Operational.dcm
  Amplifier_Operational.lib
  Comparator.dcm
  Comparator.lib
Labels: Bug, Enhancement

#2080 N-Channel HEXFET Power Mosfet IRLML0030 added
  Transistor_FET.dcm
  Transistor_FET.lib
Labels: Addition, Pending reviewer

#2065 add NCP718 linear regulators as alias to lp5907
  Regulator_Linear.dcm
  Regulator_Linear.lib
Labels: Addition, Pending reviewer

#2064 add CPC1117N as alias to CPC1017
  Relay_SolidState.dcm
  Relay_SolidState.lib
Labels: Addition

#2151 Change GPIO pins back to Bidirectional for Microchip ATmega symbols
  MCU_Microchip_ATmega.lib
Labels: Bug, Pending reviewer

#2150 Change GPIO pins back to Bidirectional for Microchip ATtiny symbols
  MCU_Microchip_ATtiny.lib
Labels: Bug

#2149 Change GPIO pins back to Bidirectional for Microchip AVR symbols
  MCU_Microchip_AVR.lib
Labels: Bug

#2139 Add some BAS16 series of diodes as ALIASes
  Diode.dcm
  Diode.lib
Labels: Addition, Pending reviewer

#2051 Add Sm420561N
  Display_Character.dcm
  Display_Character.lib
Labels: Addition

#2141 Correct pin numbers on LF398_ symbols
  Analog.lib
Labels: Bug, Enhancement

#2118 Add ATSAMD51J18/19/20A
  MCU_Microchip_SAMD.dcm
  MCU_Microchip_SAMD.lib
Labels: Addition

#2162 Fix 74LS192/193
  74xx.dcm
  74xx.lib
  74xx_IEEE.dcm
  74xx_IEEE.lib
Labels: Bug, Enhancement

#2131 BAV99 fixes
  Diode.dcm
  Diode.lib
Labels: Bug

#2092 Add the TI TS3A27518E 6-channel 1:2 analog mux
  Analog_Switch.dcm
  Analog_Switch.lib
Labels: Addition

#2076 Fix 74LVC1G66
  74xGxx.dcm
  74xGxx.lib
Labels: Bug, Enhancement, Ready for review

#2182 Add Sc4503
  Regulator_Switching.dcm
  Regulator_Switching.lib
Labels: Addition, Re-push

#2179 Add a few BJTs
  Transistor_BJT.dcm
  Transistor_BJT.lib
Labels: Addition, Bug, Pending reviewer

#1010 I80186 i80188
  MCU_Intel.dcm
  MCU_Intel.lib
Labels: Addition

#2183 Fix the assigned TSSOP footprint
  Driver_Display.dcm
  Driver_Display.lib
Labels: Bug

#2109 Add R_Pack04_Split
  Device.dcm
  Device.lib
Labels: Addition, Pending reviewer

#2137 Add microMELF diode symbols
  Diode.dcm
  Diode.lib
Labels: Addition

#1984 Relay and Relay_SolidState symbol cleanup
  Relay.lib
  Relay_SolidState.lib
Labels: Bug, Enhancement

#1861 Converter_ACDC: Add CUI PBO power supply series
  Converter_ACDC.dcm
  Converter_ACDC.lib
Labels: Addition, Pending footprint

#2188 Add OPAx197 op amps
  Amplifier_Operational.dcm
  Amplifier_Operational.lib
Labels: Addition

#2195 Add LTC4317 Dual I2C/SMBus Address-Translator
  Interface.dcm
  Interface.lib
Labels: Addition

#2197 Fixed IGBT Arrow direction (#2196)
  Device.lib
  Transistor_IGBT.lib
Labels: Bug, Pending reviewer

#2164 Fix AVR ISP connectors
  Connector.dcm
  Connector.lib
Labels: Enhancement, Pending reviewer, Ready for review

#2059 Add AVR-UPDI-6
  Connector.dcm
  Connector.lib
Labels: Addition, Pending reviewer, Ready for review

#1923 Add LT3471
  Regulator_Switching.dcm
  Regulator_Switching.lib
Labels: Addition, Enhancement, Pending changes

#2193 Added FAN3278
  Driver_FET.dcm
  Driver_FET.lib
Labels: Addition, Pending reviewer

#2205 Added OPA196, OPA2196 and OPA419
  Amplifier_Operational.dcm
  Amplifier_Operational.lib
Labels: Addition, Re-push

#2194 Add MAX6035 vrefs, SOT-23/SOIC-8
  Reference_Voltage.dcm
  Reference_Voltage.lib
Labels: Addition

#2199 Add three new transistors as ALIASes
  Transistor_BJT.dcm
  Transistor_BJT.lib
Labels: Addition, Enhancement

#2187 Add BCV[24]9 NPN Darlington
  Transistor_BJT.dcm
  Transistor_BJT.lib
Labels: Addition

#2144 Add Lattice ICE40HX4K-TQ144
  FPGA_Lattice.dcm
  FPGA_Lattice.lib
Labels: Addition, Pending reviewer

#2189 Adding TPS565208 (TPS562200 alias)
  Regulator_Switching.dcm
  Regulator_Switching.lib
Labels: Addition

#2201 Add BZX384 zener diode
  Diode.dcm
  Diode.lib
Labels: Addition

#2198 Add Texas Instruments LPV811 and LPV812, nano power operational amplifiers
  Amplifier_Operational.dcm
  Amplifier_Operational.lib
Labels: Addition, Bug, Pending changes

#1948 Interface_UART: Add SC16IS740
  Interface_UART.dcm
  Interface_UART.lib
Labels: Addition, Pending changes

#1937 add Schaffner FN405 line filter
  Filter.dcm
  Filter.lib
Labels: Addition, Pending reviewer

#2091 Add symbol for FTDI FT4222HQ
  Interface_USB.dcm
  Interface_USB.lib
Labels: Addition, Pending reviewer

#2079 New Symbol THVD1451 (RS485 line driver)
  Interface_UART.dcm
  Interface_UART.lib
Labels: Addition

#1997 Add new high-power SMD diodes
  Diode.dcm
  Diode.lib
Labels: Addition
