Repository KiCad/kicad-symbols, pull requests merged in 2019-01, with the labels that each got.

#1361 Add blank datasheet URLs for generic switch symbols
  Switch.dcm
Labels: Bug

#1027 Add Infineon IM69D1x0 MEMS microphones
  Sensor_Audio.dcm
  Sensor_Audio.lib
Labels: Addition, Pending footprint

#1360 Added Microchip/Micrel MIC5365/6-3.3Volt LDO
  Regulator_Linear.dcm
  Regulator_Linear.lib
Labels: Addition

#1358 Fix KLC S3.3 and S3.6 on MCU_Cypress.lib
  MCU_Cypress.lib
Labels: Bug

#1351 Added Diodes SD103ATW 3xSchottky array SOT-363 (finish #655)
  Diode.dcm
  Diode.lib
Labels: Addition

#1336 Add TUSB320, TUSB321, TUSB322I
  Interface_USB.dcm
  Interface_USB.lib
Labels: Addition

#1349 Add TI BQ2501x 500mA Li-Ion Charger (finish #423)
  Battery_Management.dcm
  Battery_Management.lib
Labels: Addition

#1352 Add ST VNH5019A-E motor driver (finish #797)
  Driver_Motor.dcm
  Driver_Motor.lib
Labels: Addition

#1265 Add ESP32-WROOM-32U
  RF_Module.dcm
  RF_Module.lib
Labels: Addition

#1111 Add SN74AVC16827DGGR
  74xx.dcm
  74xx.lib
Labels: Addition

#1208 Add Mini-Circuits ADE-6
  RF.dcm
  RF.lib
Labels: Addition

#1215 add Mini-Circuits SXBP-series bandpass filter
  RF.dcm
  RF.lib
Labels: Addition

#1216 add Mini-Circuits LRPS-2-1 power splitter/combiner
  RF.dcm
  RF.lib
Labels: Addition, Pending footprint

#1041 Added BQ51051B/BQ51051B/BQ51052B with package DSBGA
  Battery_Management.dcm
  Battery_Management.lib
Labels: Addition

#1279 Add AD630ARZ in SOIC-20W
  Analog.dcm
  Analog.lib
Labels: Addition

#1219 add Mini-Circuits High Pass Filter SCHF-31+
  RF.dcm
  RF.lib
Labels: Addition

#1209 Add Mini-Circuits RMK-5-51 frequency multiplier
  RF.dcm
  RF.lib
Labels: Addition

#1200 Mini-Circuits AMK-2-13 2x frequency multiplier
  RF.dcm
  RF.lib
Labels: Addition

#1218 add Mini-Circuits RBP-280 bandpass filter
  RF.dcm
  RF.lib
Labels: Addition

#1372 ADP-2-1W
  RF.dcm
  RF.lib
Labels: Addition

#1314 MCU_ST_STM8: Add STM8L152x
  MCU_ST_STM8.dcm
  MCU_ST_STM8.lib
Labels: Addition

#1373 RLP-30
  RF.dcm
  RF.lib
Labels: Addition, Re-push

#1224 add Mini-Circuits directional coupler ADC-10-1R
  RF.dcm
  RF.lib
Labels: Addition

#1226 add Mini-Circuits attenuator LAT-3
  RF.dcm
  RF.lib
Labels: Addition

#1051 Align BTS* symbols
  Power_Management.lib
Labels: Enhancement

#1381 Add MAX5215 and MAX5217
  Analog_DAC.dcm
  Analog_DAC.lib
Labels: Addition

#1064 Cypress touch sensor fix
  Sensor_Touch.lib
Labels: Enhancement

#1311 Add CDP1802ACE
  CPU.dcm
  CPU.lib
Labels: Addition

#1109 Add HT9170D
  Interface_Telecom.dcm
  Interface_Telecom.lib
Labels: Addition

#1384 fix part spelling for TPS79333-EP
  Regulator_Linear.dcm
  Regulator_Linear.lib
Labels: Bug

#954 Add EMI2121MTTAG
  Power_Protection.dcm
  Power_Protection.lib
Labels: Addition

#1389 Fix 4046 pinout
  4xxx.lib
  4xxx_IEEE.lib
Labels: Bug

#1388 Fix some invalid NXP URLs
  4xxx.dcm
  74xx.dcm
  Diode.dcm
  Power_Protection.dcm
  Timer_RTC.dcm
  Transistor_BJT.dcm
  Triac_Thyristor.dcm
  Video.dcm
Labels: Enhancement, Pending reviewer

#1199 add JTOS-50 VCXO with alias JTOS-25
  Oscillator.dcm
  Oscillator.lib
Labels: Addition

#1206 Added CD4098. (take2)
  4xxx.dcm
  4xxx.lib
Labels: Addition

#1397 FPGA_Lattice*, Interface_UART*: drop unnecessary execute permission
  FPGA_Lattice.dcm
  FPGA_Lattice.lib
  Interface_UART.dcm
  Interface_UART.lib
Labels: Enhancement

#1173 new symbol: VCXO Abracon Ablno
  Oscillator.dcm
  Oscillator.lib
Labels: Addition

#1072 Add MICRF220AYQS
  RF.dcm
  RF.lib
Labels: Addition

#1342 add ISO1050 in SO-8
  Interface_CAN_LIN.dcm
  Interface_CAN_LIN.lib
Labels: Addition

#1402 Add NC7SVU04P5X.
  74xGxx.dcm
  74xGxx.lib
Labels: Addition

#1284 74xx: Add 74LV8154
  74xx.dcm
  74xx.lib
Labels: Addition

#1195 MCU Module: create VisionSOM boards
  MCU_Module.dcm
  MCU_Module.lib
Labels: Addition, Question

#1387 Added ADA4940-2.
  Amplifier_Difference.dcm
  Amplifier_Difference.lib
Labels: Addition

#1338 add Bourns common-mode EMI filter
  Device.dcm
  Device.lib
Labels: Addition

#1033 Add THAT Corp mic preamp ICs
  Audio.dcm
  Audio.lib
Labels: Addition

#1401 Add ADF4158.
  Timer_PLL.dcm
  Timer_PLL.lib
Labels: Addition

#1386 Added 74LVC1GU04DRL.
  74xGxx.dcm
  74xGxx.lib
Labels: Addition

#1112 add ADG901/902 and ADG918/919 RF switches
  RF_Switch.dcm
  RF_Switch.lib
Labels: Addition

#825 Add ADAU145x SigmaDSPs
  DSP_AnalogDevices.dcm
  DSP_AnalogDevices.lib
Labels: Addition

#1408 Driver_Motor: Add DRV883x
  Driver_Motor.dcm
  Driver_Motor.lib
Labels: Addition, Re-push

#1396 Add ICS525-01/-02 User configurable clock with pll
  Timer_PLL.dcm
  Timer_PLL.lib
Labels: Addition

#1150 Add several generic BRT symbols
  Device.dcm
  Device.lib
Labels: Addition

#1370 add LT1711 in MSOP-8
  Comparator.dcm
  Comparator.lib
Labels: Addition

#1239 add ADR420-series voltage references in MSOP-8
  Reference_Voltage.dcm
  Reference_Voltage.lib
Labels: Addition

#1367 Add LTC4156 (USB/LiFePo4 Charger/PMIC)
  Battery_Management.dcm
  Battery_Management.lib
Labels: Addition

#1231 add LTC6993 pulse generator
  Timer.dcm
  Timer.lib
Labels: Addition

#1363 Added symbol for Silicon Labs Si512/513 dual frequency oscillator
  Oscillator.dcm
  Oscillator.lib
Labels: Addition

#1414 Add TLV172IDCK.
  Amplifier_Operational.dcm
  Amplifier_Operational.lib
Labels: Addition

#958 Add ATSAME53J18A-AN
  MCU_Microchip_SAME.dcm
  MCU_Microchip_SAME.lib
Labels: Addition

#1234 add LMH6702MF+LMH6609MF as variant of existing symbol
  Amplifier_Operational.dcm
  Amplifier_Operational.lib
Labels: Addition

#1269 Add MSP432E401Y, TLV2371, TLV2372, TLV62568, LM4128, TPS61041, CDNBS0…
  Amplifier_Operational.dcm
  Amplifier_Operational.lib
  MCU_Texas.dcm
  MCU_Texas.lib
  Power_Protection.dcm
  Power_Protection.lib
  Reference_Voltage.dcm
  Reference_Voltage.lib
  Regulator_Switching.dcm
  Regulator_Switching.lib
Labels: Addition

#1174 OCXO OH300
  Oscillator.dcm
  Oscillator.lib
Labels: Addition

#1411 Add CP2102N QFN28
  Interface_USB.dcm
  Interface_USB.lib
Labels: Addition

#1172 MV267 symbol, with variant MV317
  Oscillator.dcm
  Oscillator.lib
Labels: Addition

#1413 Add TRF37A73.
  RF_Amplifier.dcm
  RF_Amplifier.lib
Labels: Addition

#927 add MSP430F2618-EP
  MCU_Texas_MSP430.dcm
  MCU_Texas_MSP430.lib
Labels: Addition

#879 add ASCO oscillators familly from manufacturer Abracon
  Oscillator.dcm
  Oscillator.lib
Labels: Addition

#1326 Add LP2980-ADJ LDO voltage regulator
  Regulator_Linear.dcm
  Regulator_Linear.lib
Labels: Addition

#1421 Sensor_Optical: Kingbright KPS-3227 ambient light sensor.
  Sensor_Optical.dcm
  Sensor_Optical.lib
Labels: Addition

#1087 Add LTC6994-2
  Timer.dcm
  Timer.lib
Labels: Addition

#1325 Add Tps6300x
  Regulator_Switching.dcm
  Regulator_Switching.lib
Labels: Addition

#1423 Add MMSD4148
  Diode.dcm
  Diode.lib
Labels: Addition

#1429 Added ADuM5410, ADuM5411 and ADuM5412
  Isolator.dcm
  Isolator.lib
Labels: Addition

#1074 TLC5957 & TLC5951
  Driver_LED.dcm
  Driver_LED.lib
Labels: Addition

#1431 Add EP to SE5004L.
  RF.lib
Labels: Addition

#1168 add murata bnx025 symbol
  Filter.dcm
  Filter.lib
Labels: Addition

#1237 Transistor_FET: Add Diodes Inc. N-Channel SOT-23 MOSFETs
  Transistor_FET.dcm
  Transistor_FET.lib
Labels: Addition

#1017 Add LAN Ethernet Transformer
  Transformer.dcm
  Transformer.lib
Labels: Addition

#1212 Add Mini-Circuits LPF-B0R3 low-pass filter
  RF.dcm
  RF.lib
Labels: Addition

#1214 add Mini-Circuits SYPD-2 phase detector
  RF.dcm
  RF.lib
Labels: Addition

#1202 Add the LED5000 LED driver from ST
  Driver_LED.dcm
  Driver_LED.lib
Labels: Addition

#1404 Add KT2520.
  Oscillator.dcm
  Oscillator.lib
Labels: Addition

#1439 Add TI SN75160B
  Interface.dcm
  Interface.lib
Labels: Addition

#1438 LT1963A fixed LDOs in SOT-223
  Regulator_Linear.dcm
  Regulator_Linear.lib
Labels: Addition

#932 Add Texas Instruments TPL5111 - Nano Power Timer, Active-High
  Timer.dcm
  Timer.lib
Labels: Addition

#1410 Add PAT1220.
  RF.dcm
  RF.lib
Labels: Addition

#1447 Add LTC4055 and LTC4055-1 (USB Power Controller and Li-Ion Charger)
  Battery_Management.dcm
  Battery_Management.lib
Labels: Addition

#1432 Add BQ24392
  Interface_USB.dcm
  Interface_USB.lib
Labels: Addition

#1448 Fix for #1442: Mini-Circuits footprint filters.
  RF.dcm
  RF.lib
Labels: Enhancement

#1449 RMK-3-451 and RMK-5-51: fix double underscore in PL-258 footprint
  RF.lib
Labels: Bug

#1434 Added symbol for ICM-20948
  Sensor_Motion.dcm
  Sensor_Motion.lib
Labels: Addition

#1451 Sensor: Set footprint of SHT1x
  Sensor.lib
Labels: Enhancement

#930 Add Texas Instruments TPL5010 - Nano Power Timer w/ Watchdog
  Timer.dcm
  Timer.lib
Labels: Addition

#1398 Added DC4759J5020AHF.
  RF.dcm
  RF.lib
Labels: Addition

#1374 Added 5400BL15B050E.
  Transformer.dcm
  Transformer.lib
Labels: Addition

#1453 add MAX394 Quad SPDT CMOS switch
  Analog_Switch.dcm
  Analog_Switch.lib
Labels: Addition

#1412 Add SKY65404.
  RF_Amplifier.dcm
  RF_Amplifier.lib
Labels: Addition

#1417 Add W25Q32JVZP
  Memory_Flash.dcm
  Memory_Flash.lib
Labels: Addition

#1456 Modified sensor DHT11
  Sensor.dcm
  Sensor.lib
Labels: Addition, Re-push

#1399 Add PD4859J5050S2HF
  RF.dcm
  RF.lib
Labels: Addition

#1463 Add XLR6 connector
  Connector.dcm
  Connector.lib
Labels: Addition

#1457 Added CHT11 as an alias to DHT11
  Sensor.dcm
  Sensor.lib
Labels: Addition

#1405 Add LTC229x.
  Analog_ADC.dcm
  Analog_ADC.lib
Labels: Addition

#1459 Moving mini circuits footprints out of Package_SO lib
  Oscillator.lib
  RF.lib
  Transformer.lib
Labels: Enhancement

#1403 Add HMC431.
  RF.dcm
  RF.lib
Labels: Addition

#1462 Diode: add BAT54W series
  Diode.dcm
  Diode.lib
Labels: Addition, Pending reviewer

#1252 Photomultiplier Tube library
  Sensor_Optical.dcm
  Sensor_Optical.lib
Labels: Addition
