Repository KiCad/kicad-symbols, pull requests merged in 2019-06, with the labels that each got.

#1870 add AAT1217 step-up converter
  Regulator_Switching.dcm
  Regulator_Switching.lib
Labels: Addition

#1900 Switch: SW_DPST_x2: make every pin passive
  Switch.lib
Labels: Bug

#1558 add AD9513, AD9514 and AD9515
  Timer.dcm
  Timer.lib
Labels: Addition, Pending footprint

#1888 Add Analog ADN4650
  Isolator.dcm
  Isolator.lib
Labels: Addition

#1878 Add Wuerth 171050601
  Regulator_Switching.dcm
  Regulator_Switching.lib
Labels: Addition

#1786 Added TPS6122x boost converters
  Regulator_Switching.dcm
  Regulator_Switching.lib
Labels: Addition

#1898 Add IS31FL3731
  Driver_LED.dcm
  Driver_LED.lib
Labels: Addition

#1539 add LP3982 linear regulators
  Regulator_Linear.dcm
  Regulator_Linear.lib
Labels: Addition

#1823 Add Texas UCC246xx sync rect controllers
  Regulator_Controller.dcm
  Regulator_Controller.lib
Labels: Addition

#1826 merged and autogenerated connector symbols up to 75 pins
  Connector_Generic.dcm
  Connector_Generic.lib
  Connector_Generic_MountingPin.dcm
  Connector_Generic_MountingPin.lib
  Connector_Generic_Shielded.dcm
  Connector_Generic_Shielded.lib
Labels: Addition

#1816 Adding small potentiometer device.
  Device.dcm
  Device.lib
Labels: Addition

#1872 Add MIC2025
  Power_Management.dcm
  Power_Management.lib
Labels: Addition, Pending footprint

#1859 Memory_Flash: Add SST25VF080B device from Microchip
  Memory_Flash.dcm
  Memory_Flash.lib
Labels: Addition

#1887 Add TI BQ24072 and BQ24074
  Battery_Management.dcm
  Battery_Management.lib
Labels: Addition

#1901 Add IS31FL3736/7
  Driver_LED.dcm
  Driver_LED.lib
Labels: Addition

#1700 ADXL343 symbol
  Sensor_Motion.dcm
  Sensor_Motion.lib
Labels: Addition

#1917 MCU_Microchip_PIC16: Fix TX pin name in PIC16f145X
  MCU_Microchip_PIC16.lib
Labels: Bug

#1918 Fix multiple greedy FP filters
  Amplifier_Buffer.lib
  Amplifier_Current.lib
  Amplifier_Operational.lib
  Battery_Management.lib
  Comparator.lib
  Diode.lib
  Driver_FET.lib
  Memory_EEPROM.lib
  Power_Supervisor.lib
  RF_Switch.lib
  Reference_Voltage.lib
  Regulator_Linear.lib
  Regulator_SwitchedCapacitor.lib
  Regulator_Switching.lib
  Sensor_Touch.lib
  Timer.lib
Labels: Bug, Enhancement

#1594 Add Analog ADV7611 HDMI Receiver
  Interface_HDMI.dcm
  Interface_HDMI.lib
Labels: Addition

#1902 Add ATAES132ASH
  Security.dcm
  Security.lib
Labels: Addition

#1906 Added NCP1529
  Regulator_Switching.dcm
  Regulator_Switching.lib
Labels: Addition

#1886 Adds Intel 8080 microprocessor
  MCU_Intel.dcm
  MCU_Intel.lib
Labels: Addition

#1838 Add Murata MGJ3 symbol
  Converter_DCDC.dcm
  Converter_DCDC.lib
Labels: Addition

#1924 Add AK7742EQ
  Audio.dcm
  Audio.lib
Labels: Addition, Pending changes

#1913 Add PCA9635
  Driver_LED.dcm
  Driver_LED.lib
Labels: Addition, Pending reviewer

#1912 Add IS31FL3218
  Driver_LED.dcm
  Driver_LED.lib
Labels: Addition, Pending reviewer

#1914 Improve IS31FL3216/A
  Driver_LED.dcm
  Driver_LED.lib
Labels: Enhancement, Pending reviewer

#1907 Added diode MBRA340 as aliases to the existing B120-E3 symbol
  Diode.dcm
  Diode.lib
Labels: Addition

#1868 Add Analog ADN4652
  Isolator.dcm
  Isolator.lib
Labels: Addition

#1883 Add NXP MCU MKV11Z128VLH7
  MCU_NXP_Kinetis.dcm
  MCU_NXP_Kinetis.lib
Labels: Addition

#1936 Add FDS9435A
  Transistor_FET.dcm
  Transistor_FET.lib
Labels: Addition, Pending reviewer

#1925 Commodore 6502 Microprocessor
  obsolete/CPU.dcm
  obsolete/CPU.lib
Labels: Addition, Pending reviewer

#1780 Battery_Management: Add BQ24133
  Battery_Management.dcm
  Battery_Management.lib
Labels: Addition

#1934 Fix checklib.py errors in MCU_Module
  MCU_Module.dcm
  MCU_Module.lib
Labels: Enhancement

#1909 Add symbol for 4021 shift register
  4xxx.dcm
  4xxx.lib
Labels: Addition

#1940 Added CD4148W
  Diode.dcm
  Diode.lib
Labels: Addition, Pending reviewer

#1939 Added AO3401A
  Transistor_FET.dcm
  Transistor_FET.lib
Labels: Addition
