Repository KiCad/kicad-symbols, pull requests merged in 2019-07, with the labels that each got.

#1921 74HC(T)164
  74xx.dcm
  74xx.lib
Labels: Addition

#1877 Add Analog LTC4365xTS8
  Power_Management.dcm
  Power_Management.lib
Labels: Addition

#1889 Add Analog ADN4651
  Isolator.dcm
  Isolator.lib
Labels: Addition

#1931 Add PL611-01 in SOT-23-6
  Timer.dcm
  Timer.lib
Labels: Addition

#1953 Fixing incorrect type for Power pins
  Driver_FET.lib
Labels: Bug

#1950 Add STGAP2S symbols
  Driver_FET.dcm
  Driver_FET.lib
Labels: Addition

#1266 Added PIC24FJ256DA210-IBG and PIC24FJ256DA210-IPT
  MCU_Microchip_PIC24.dcm
  MCU_Microchip_PIC24.lib
Labels: Addition, Re-push

#1495 Add PCA9548 I2C multiplexer
  Interface_Expansion.dcm
  Interface_Expansion.lib
Labels: Addition, Pending footprint

#1938 Added AP65111
  Regulator_Switching.dcm
  Regulator_Switching.lib
Labels: Addition, Re-push

#1642 - added TI SM72295 Full Bridge Mosfet Driver
  Driver_FET.dcm
  Driver_FET.lib
Labels: Addition

#1970 Change BC8[45]6BS footprint filters
  Transistor_BJT.lib
Labels: Enhancement

#1988 Added Texas Instruments TPS61252 switching regulator (tiny adjustable…
  Regulator_Switching.dcm
  Regulator_Switching.lib
Labels: Addition

#1867 Add Texas Instruments CDCLVP1102
  Interface.dcm
  Interface.lib
Labels: Addition

#1444 Add Mini-Circuits RF switches KSW(A)-2-46 and KSWHA-1-20
  RF_Switch.dcm
  RF_Switch.lib
Labels: Addition, Pending footprint

#1930 added TLV9004xRUCR
  Amplifier_Operational.dcm
  Amplifier_Operational.lib
Labels: Addition

#2016 add CD4097B
  Analog_Switch.dcm
  Analog_Switch.lib
Labels: Addition, Pending reviewer

#2005 Add MAX14778 multiplexer
  Analog_Switch.dcm
  Analog_Switch.lib
Labels: Addition, Pending reviewer

#2032 Change footprint for the APA102 5050
  LED.lib
Labels: Bug

#2035 Fix 4068 IEEE symbol
  4xxx_IEEE.dcm
  4xxx_IEEE.lib
Labels: Bug

#2037 Added BAT60A
  Diode.dcm
  Diode.lib
Labels: Addition

#2043 Correct Motor/Fan_ALT symbol
  Motor.dcm
  Motor.lib
Labels: Bug
