Repository KiCad/kicad-symbols, pull requests merged in 2019-11, with the labels that each got.

#2269 added AS13704
  Amplifier_Operational.dcm
  Amplifier_Operational.lib
Labels: Addition, Pending reviewer

#2267 Add ARJP11A-MASA-B-A-EMU2 RJ45 connector
  Connector.dcm
  Connector.lib
Labels: Addition, Pending changes

#2136 Clean up Arduino modules
  MCU_Module.lib
Labels: Enhancement, Pending reviewer

#2276 [Inteface_USB/MCP2210] Swap USB and SPI pins positions
  Interface_USB.dcm
  Interface_USB.lib
Labels: Enhancement

#2253 Add Potentiometer AD5254
  Potentiometer_Digital.dcm
  Potentiometer_Digital.lib
Labels: Addition, Pending changes

#2286 Adding TLV62569 (TLV62568 aliases)
  Regulator_Switching.dcm
  Regulator_Switching.lib
Labels: Addition, Pending reviewer

#2289 Adding SN75176A (SN75LBC176 aliases)
  Interface_UART.dcm
  Interface_UART.lib
Labels: Addition, Bug, Pending changes

#1896 7 seg symbol
  Display_Character.dcm
  Display_Character.lib
Labels: Addition

#2247 Add LP5036 LED driver
  Driver_LED.dcm
  Driver_LED.lib
Labels: Addition, Pending changes

#2311 Fix the output pins of LTC6362* devices which were marked as power in…
  Amplifier_Operational.lib
Labels: Bug

#2257 Add LT3756xMSE buck/boost/sepic 100V LED driver
  Driver_LED.dcm
  Driver_LED.lib
Labels: Addition, Pending changes

#2303 Transistor_FET: Add FQP27P06
  Transistor_FET.dcm
  Transistor_FET.lib
Labels: Addition, Pending reviewer

#2307 Added TSM2301ACXRFG, alias of TP0610T.
  Transistor_FET.dcm
  Transistor_FET.lib
Labels: Addition, Pending changes

#2319 Add MCP23008 i2c IO expander
  Interface_Expansion.dcm
  Interface_Expansion.lib
Labels: Addition

#2243 Adding XUx5x and XUx7x IDT oscillators
  Oscillator.dcm
  Oscillator.lib
Labels: Addition

#2338 SW_MEC_5G: Making pin visible
  Switch.lib
Labels: Enhancement, Pending reviewer
