Repository KiCad/kicad-symbols, pull requests merged in 2019-03, with the labels that each got.

#1579 Add IRM-03, -05, and -10 symbols
  Converter_ACDC.dcm
  Converter_ACDC.lib
Labels: Addition, Enhancement

#1589 Fix pin numbering for Omron G6K relays.
  Relay.lib
Labels: Bug, Pending reviewer

#1133 Add LT3032 and variants
  Regulator_Linear.dcm
  Regulator_Linear.lib
Labels: Addition, Pending footprint

#1572 MCU_Microchip_PIC16: Add PIC16F18325-xGZ
  MCU_Microchip_PIC16.dcm
  MCU_Microchip_PIC16.lib
Labels: Addition

#1576 Battery_Management: Add BQ24005 and BQ24006
  Battery_Management.dcm
  Battery_Management.lib
Labels: Addition

#1319 added LM5001MAx
  Regulator_Switching.dcm
  Regulator_Switching.lib
Labels: Addition

#1591 Add TCAN1043xDxQ1 SOIC-14 CAN-FD Transceivers
  Interface_CAN_LIN.dcm
  Interface_CAN_LIN.lib
Labels: Addition

#1565 Connector/Conn_ARM_JTAG_SWD_10: fix pin names, types and link.
  Connector.dcm
  Connector.lib
Labels: Enhancement

#1592 fixed pins of 74157
  74xx.lib
Labels: Bug

#1597 Adding NCV8114 LDOs
  Regulator_Linear.dcm
  Regulator_Linear.lib
Labels: Addition

#1584 Add MP171
  Regulator_Switching.dcm
  Regulator_Switching.lib
Labels: Addition

#1588 adding Texas Instruments INA253 current sensor, advice needed
  Amplifier_Current.dcm
  Amplifier_Current.lib
Labels: Addition

#1571 Fix footprint of TCA9535DBR
  Interface_Expansion.lib
Labels: Bug

#1394 Correct TI TUSB7340 footprint name
  Interface_USB.lib
Labels: Bug

#1605 add Lis3dh
  Sensor_Motion.dcm
  Sensor_Motion.lib
Labels: Addition

#1612 TE Miniature PCB Relay PCH
  Relay.dcm
  Relay.lib
Labels: Addition, Re-push

#1596 Add Texas Instruments TPD12S520DBT HDMI Receiver Port Protection and …
  Interface_HDMI.dcm
  Interface_HDMI.lib
  sym-lib-table
Labels: Addition

#1524 Add 3-Port Gigabit Ethernet Switch KSZ9893RNX
  Interface_Ethernet.dcm
  Interface_Ethernet.lib
Labels: Addition

#1460 Fix typo in dual opamp aliases list and add another opamp
  Amplifier_Operational.dcm
  Amplifier_Operational.lib
  MCU_Microchip_SAMD.dcm
  MCU_Microchip_SAMD.lib
Labels: Addition, Bug

#1616 Added Si7141DP
  Transistor_FET.dcm
  Transistor_FET.lib
Labels: Addition

#1615 Added 2N7002K
  Transistor_FET.dcm
  Transistor_FET.lib
Labels: Addition, Ready for review

#1619 Make component descriptions consistent
  74xx.dcm
  Amplifier_Audio.dcm
  Amplifier_Current.dcm
  Amplifier_Instrumentation.dcm
  Amplifier_Operational.dcm
  Analog_DAC.dcm
  Battery_Management.dcm
  Diode_Laser.dcm
  Display_Character.dcm
  Driver_FET.dcm
  Interface.dcm
  Isolator.dcm
  Logic_LevelTranslator.dcm
  Reference_Voltage.dcm
  Regulator_Linear.dcm
  Regulator_SwitchedCapacitor.dcm
  Regulator_Switching.dcm
  Relay.dcm
  Relay_SolidState.dcm
  Timer.dcm
  Transistor_FET.dcm
  Triac_Thyristor.dcm
Labels: Enhancement

#727 added WemosD1Mini after accidentally deleting it
  MCU_Module.dcm
  MCU_Module.lib
Labels: Addition

#1611 added ATSAME51J**A-AU
  MCU_Microchip_SAME.dcm
  MCU_Microchip_SAME.lib
Labels: Addition, Re-push

#729 Add PocketBeagle
  MCU_Module.dcm
  MCU_Module.lib
Labels: Addition

#1120 Added atomic part and dcm data for PIC18(L)F25/26K83 in the narrow DI…
  MCU_Microchip_PIC18.dcm
  MCU_Microchip_PIC18.lib
Labels: Addition, Pending changes

#1176 Move CH376 from Memory_Controller to to Interface (#1144)
  Interface.dcm
  Interface.lib
  Memory_Controller.dcm
  Memory_Controller.lib
  sym-lib-table
Labels: Enhancement, Pending reviewer

#1458 Fix #1272 - Update LT3010 with proper naming
  Regulator_Linear.dcm
  Regulator_Linear.lib
Labels: Bug

#1602 Add SN74CBT3253
  Analog_Switch.dcm
  Analog_Switch.lib
Labels: Addition

#1625 Fix small gnd crystal ground pin location
  Device.dcm
  Device.lib
Labels: Enhancement

#1540 Fix up pins on a few triangle symbols
  Amplifier_Difference.lib
  Amplifier_Operational.lib
  Audio.lib
Labels: Enhancement

#1614 TPS5430x
  Regulator_Switching.dcm
  Regulator_Switching.lib
Labels: Addition

#1613 Added ICM-20602
  Sensor_Motion.dcm
  Sensor_Motion.lib
Labels: Addition

#1627 MS5611 Pressure Sensor
  Sensor_Pressure.dcm
  Sensor_Pressure.lib
Labels: Addition

#1626 added AD7794/AD7795 ADC
  Analog_ADC.dcm
  Analog_ADC.lib
Labels: Addition

#1628 Added IST8310 and IST8308
  Sensor_Magnetic.dcm
  Sensor_Magnetic.lib
Labels: Addition

#1624 Removed placeholder x form PIC18(L)F25/26K83x-x_SP. It is now PIC18(L…
  MCU_Microchip_PIC18.dcm
  MCU_Microchip_PIC18.lib
Labels: Enhancement

#1620 Add PCM5121/PCM5122
  Audio.dcm
  Audio.lib
Labels: Addition

#1603 Add Si5351x-B-Gx
  Oscillator.dcm
  Oscillator.lib
Labels: Addition

#1333 Zilog Z80 PIO Parallel I/O DIP-40
  Interface.dcm
  Interface.lib
Labels: Addition

#1590 Add PIC16F1786-xML
  MCU_Microchip_PIC16.dcm
  MCU_Microchip_PIC16.lib
Labels: Addition

#1543 add AAT4610B
  Power_Management.dcm
  Power_Management.lib
Labels: Addition

#1544 add AAT4616IGV
  Power_Management.dcm
  Power_Management.lib
Labels: Addition

#1639 Logic_LevelTranslator: Add TI SN74AVC8T245PW
  Logic_LevelTranslator.dcm
  Logic_LevelTranslator.lib
Labels: Addition

#1640 Timer_PLL: add Cirrus CS2000-CP
  Timer_PLL.dcm
  Timer_PLL.lib
Labels: Addition

#1644 Add AS6C4008-55PCN
  Memory_RAM.dcm
  Memory_RAM.lib
Labels: Addition

#1655 add AD9912 DDS
  Interface.dcm
  Interface.lib
Labels: Addition

#1663 Addition - DMG2301L
  Transistor_FET.dcm
  Transistor_FET.lib
Labels: Addition

#1648 Create VTX-214-010 family
  Converter_ACDC.dcm
  Converter_ACDC.lib
Labels: Addition

#1671 Clearer descriptions for power symbols
  power.dcm
Labels: Enhancement

#1674 Add MP1470
  Regulator_Switching.dcm
  Regulator_Switching.lib
Labels: Addition

#1645 74xx: Add 74HC4024
  74xx.dcm
  74xx.lib
Labels: Addition

#1601 Add NCN4555MNR2G
  Logic_LevelTranslator.dcm
  Logic_LevelTranslator.lib
Labels: Addition

#1669 Add lt8303
  Regulator_Switching.dcm
  Regulator_Switching.lib
Labels: Addition

#1445 Fix Issue1391
  RF_AM_FM.dcm
  RF_AM_FM.lib
  RF_Module.dcm
  RF_Module.lib
Labels: Bug

#1485 Fix fp for LM2574HVM (correct body size number format)
  Regulator_Switching.lib
Labels: Enhancement

#1686 Added TSV994
  Amplifier_Operational.dcm
  Amplifier_Operational.lib
Labels: Addition, Re-push

#1665 Add 74LS07
  74xx.dcm
  74xx.lib
Labels: Addition

#1666 Add DMC2053UVT
  Transistor_FET.dcm
  Transistor_FET.lib
Labels: Addition

#1108 Add STC15W201S series
  MCU_STC.dcm
  MCU_STC.lib
  sym-lib-table
Labels: Addition

#1409 Relay: Add RT3 family
  Relay.dcm
  Relay.lib
Labels: Addition

#1424 RF Module: Add CMWX1ZZABZ
  RF_Module.dcm
  RF_Module.lib
Labels: Addition

#1684 Added ZXMP4A16GTA P-Channel FET
  Transistor_FET.dcm
  Transistor_FET.lib
Labels: Addition

#1683 TXB0304RUT and TXBN0304RUT
  Logic_LevelTranslator.dcm
  Logic_LevelTranslator.lib
Labels: Addition

#1600 Create LT3748
  Regulator_Switching.dcm
  Regulator_Switching.lib
Labels: Addition

#1647 Add AP9101 symbols
  Battery_Management.dcm
  Battery_Management.lib
Labels: Addition

#1599 Onion2 s
  MCU_Module.dcm
  MCU_Module.lib
Labels: Addition

#1583 Add W25Q32JVSS.
  Memory_Flash.dcm
  Memory_Flash.lib
Labels: Addition

#1556 TLP3123
  Relay_SolidState.dcm
  Relay_SolidState.lib
Labels: Addition, Pending footprint, Pending reviewer

#1569 ISO1211 + ISO1212
  Isolator.dcm
  Isolator.lib
Labels: Addition
