Repository KiCad/kicad-symbols, pull requests merged in 2019-08, with the labels that each got.

#2040 added diodes inc ZXBM5210
  Driver_Motor.dcm
  Driver_Motor.lib
Labels: Addition

#2018 Microchip PIC ICSP connector
  Connector.dcm
  Connector.lib
Labels: Addition, Pending changes

#2030 Sensor_Humidity: HDC1080: disconnect DAP (EP)
  Sensor_Humidity.lib
Labels: Bug

#2057 change pins of RF splitters to passive
  RF.lib
Labels: Enhancement

#2025 Add AD831
  RF_Mixer.dcm
  RF_Mixer.lib
Labels: Addition

#1343 Add INA3221 shunt and bus voltage monitor
  Power_Management.dcm
  Power_Management.lib
Labels: Addition, Pending footprint

#2053 Add Analog Devices LTC2942 and LTC2942-1
  Battery_Management.dcm
  Battery_Management.lib
Labels: Addition, Pending reviewer

#2055 Add Vishay Siliconix SiP32431 and SiP32432
  Power_Management.dcm
  Power_Management.lib
Labels: Addition, Pending reviewer

#2067 RF_Module: ESP32-WROOM-32 GND pad pin 39
  RF_Module.lib
Labels: Bug

#2071 Added PCA9600D & PCA9600DP.
  Interface.dcm
  Interface.lib
Labels: Addition, Pending changes

#2052 Add MAX7219
  Driver_LED.dcm
  Driver_LED.lib
Labels: Addition

#2077 Fix LM4810
  Amplifier_Audio.dcm
Labels: Bug

#1911 Added symbol for STM8S001J3.
  MCU_ST_STM8.dcm
  MCU_ST_STM8.lib
Labels: Addition, Pending footprint

#2013 Add PIC18F47J53
  MCU_Microchip_PIC18.dcm
  MCU_Microchip_PIC18.lib
Labels: Addition

#2082 ESP32-PICO-D4 added
  RF_Module.dcm
  RF_Module.lib
Labels: Addition

#1981 Add XC6206
  Regulator_Linear.dcm
  Regulator_Linear.lib
Labels: Addition, Librarian

#1723 UEXT connector
  Connector.dcm
  Connector.lib
Labels: Addition
