Repository KiCad/kicad-symbols, pull requests merged in 2019-12, with the labels that each got.

#2225 Addition of MAX1615 Linear Regulator for Notebooks
  Regulator_Linear.dcm
  Regulator_Linear.lib
Labels: Addition, Pending changes

#2326 Added TVS0500DRV
  Power_Protection.dcm
  Power_Protection.lib
Labels: Addition

#2134 Adding the AD9984AKST (repush from #783)
  Video.dcm
  Video.lib
Labels: Addition, Re-push

#2358 Added PMEG6030EP & PMEG6045ETP as alias of PMEG4050EP
  Diode.dcm
  Diode.lib
Labels: Addition, Pending reviewer

#2355 Add 2pin and 3pin heatsink symbols
  Mechanical.dcm
  Mechanical.lib
Labels: Addition, Pending reviewer

#2368 Update heatsink FP filters
  Mechanical.lib
Labels: Bug, Enhancement

#1659 Add Honeywell CSLW Current Sensor
  Sensor_Current.dcm
  Sensor_Current.lib
Labels: Addition

#2330 FSUSB42MUX: Addition of USB2.0 switch
  Interface_USB.dcm
  Interface_USB.lib
Labels: Addition

#2353 Addition of OPA1692 as a variant
  Amplifier_Operational.dcm
  Amplifier_Operational.lib
Labels: Addition

#2320 TC7662Bx0A and TC7662BxPA V+ was misplaced.
  Converter_DCDC.lib
Labels: Bug

#2357 Added TVSxx00 family as alias of TVS0500
  Power_Protection.dcm
  Power_Protection.lib
Labels: Addition, Pending reviewer

#1980 Add Device/LED_ARBG
  Device.dcm
  Device.lib
Labels: Addition, Pending reviewer

#2378 Fix CD4053 pinout (14/15 swapped)
  Analog_Switch.lib
Labels: Bug, Enhancement, Pending reviewer

#2295 Improve some package descriptions
  Interface_CAN_LIN.dcm
  Interface_Ethernet.dcm
  Interface_Expansion.dcm
  Interface_UART.dcm
  Interface_USB.dcm
  RF.dcm
  RF_Module.lib
  Regulator_Linear.dcm
Labels: Enhancement, Good first issue

#2377 PCF85263 / PCF85363: Create new RTC devices
  Timer_RTC.dcm
  Timer_RTC.lib
Labels: Addition

#2383 Updated jumper FP filters
  Device.lib
  Jumper.lib
Labels: Enhancement

#2382 Allow 2-pin PTCs to use R footprints
  Device.lib
Labels: Enhancement

#1958 Adding the 74CBTLV16212 (24bit bus-exchange)
  74xx.dcm
  74xx.lib
Labels: Addition, Pending changes

#933 Adding 88SE9125C0-NAA PCIe SATA controller
  Interface.dcm
  Interface.lib
Labels: Addition

#1595 Adding MX25R3235F (except 12-WLCSP and USON-8 packages)
  Memory_Flash.dcm
  Memory_Flash.lib
Labels: Addition

#2385 Add TestPoint_Small
  Connector.dcm
  Connector.lib
Labels: Addition

#2323 Adding MT3608 asynchronous DC-DC boost (step-up) converter.
  Regulator_Switching.dcm
  Regulator_Switching.lib
Labels: Addition, Pending changes

#2386 Diode_Bridge: Add aliases of B40R: RB151..RB157
  Diode_Bridge.dcm
  Diode_Bridge.lib
Labels: Addition

#2379 Add Microchip ATF1502AS(V,L) and ATF1504AS(V,L)
  CPLD_Microchip.dcm
  CPLD_Microchip.lib
  sym-lib-table
Labels: Addition

#2363 Addition of LM92 I2C Temperature Sensor
  Sensor_Temperature.dcm
  Sensor_Temperature.lib
Labels: Addition, Pending changes

#1622 Added LTC4370
  Power_Management.dcm
  Power_Management.lib
Labels: Addition

#2392 Allow 2-pin NTCs to use R footprints
  Device.lib
Labels: Enhancement

#2391 Fix IRM-03-3.3 pin name and pin number is reversed.
  Converter_ACDC.lib
Labels: Bug

#2381 Standardize testpoint-like power symbols
  power.lib
Labels: Enhancement

#1585 Add SKY13575-639LF.
  RF_Switch.dcm
  RF_Switch.lib
Labels: Addition

#2369 Change HIP2100 HB pin to Passive type
  Driver_FET.lib
Labels: Enhancement

#1949 Change Power Integrations S pin to Power Input type
  Regulator_Switching.lib
Labels: Enhancement

#2366 Create TPS22810DRV
  Power_Management.dcm
  Power_Management.lib
Labels: Addition

#2321 Adding PIC16F18324-xSL
  MCU_Microchip_PIC16.dcm
  MCU_Microchip_PIC16.lib
Labels: Addition

#2371 Fix active-low input prefixes
  74xx_IEEE.lib
  Interface_USB.lib
  MCU_Module.lib
  RF_AM_FM.lib
  RF_Module.lib
  Sensor_Motion.lib
Labels: Bug, Pending changes

#2413 Add MCP4017, MCP4018 and MCP4019
  Potentiometer_Digital.dcm
  Potentiometer_Digital.lib
Labels: Addition, Re-push

#2412 Add TLV75801P
  Regulator_Linear.dcm
  Regulator_Linear.lib
Labels: Addition, Pending changes
