Repository KiCad/kicad-symbols, pull requests merged in 2019-10, with the labels that each got.

#1999 Small update of FTDI symbols
  Interface_USB.dcm
  Interface_USB.lib
Labels: Enhancement

#2000 Add D2PAK diodes with NC pin 1
  Device.dcm
  Device.lib
Labels: Addition

#2169 Added MCP4251
  Potentiometer_Digital.dcm
  Potentiometer_Digital.lib
Labels: Addition, Pending changes

#2235 add Si2371 diode as alias
  Transistor_FET.dcm
  Transistor_FET.lib
Labels: Addition

#2224 Add EL817 optocoupler
  Isolator.dcm
  Isolator.lib
Labels: Addition, Pending reviewer

#2204 Add CAP200DG and CAP300DG as ALIAS
  Power_Management.dcm
  Power_Management.lib
Labels: Addition

#2223 Add AT45DB161D-SU DataFlash
  Memory_Flash.dcm
  Memory_Flash.lib
Labels: Addition

#2206 Adding 93AAxxAT-xOT and 93AAxxBT-xOT
  Memory_EEPROM.dcm
  Memory_EEPROM.lib
Labels: Addition, Pending reviewer

#2222 add symbols for the AOZ128xCI family of switchers
  Regulator_Switching.dcm
  Regulator_Switching.lib
Labels: Addition

#2239 Fixed symbol with boundingbox offset
  CPU.lib
Labels: Enhancement, Pending reviewer

#2241 Fix NCS2325DM op-amp FP
  Amplifier_Operational.lib
Labels: Enhancement, Pending reviewer

#2232 Add LME49600 high current audio buffer
  Amplifier_Audio.dcm
  Amplifier_Audio.lib
Labels: Addition

#2217 New part MQ-6
  Sensor_Gas.dcm
  Sensor_Gas.lib
Labels: Addition

#2226 Addition of symbol for APA-106-F5 5mm Addressable RGB LED
  LED.dcm
  LED.lib
Labels: Addition

#2192 Adding TLV755xxPDRV, TLV757xxPDRV
  Regulator_Linear.dcm
  Regulator_Linear.lib
Labels: Addition

#2244 Adding W25Q128JVS (W25Q32JVSS alias)
  Memory_Flash.dcm
  Memory_Flash.lib
Labels: Addition

#2094 Add the MCP2210 USB-to-SPI Converter
  Interface_USB.dcm
  Interface_USB.lib
Labels: Addition

#2173 Add SG5032/SG7050 Oscillators
  Oscillator.dcm
  Oscillator.lib
Labels: Addition

#2176 Added LD1086
  Regulator_Linear.dcm
  Regulator_Linear.lib
Labels: Addition

#2229 add RJ45 ethernet connector Pulse JXD6-0001NL
  Connector.dcm
  Connector.lib
Labels: Addition

#1959 Adding LM810/809 (Microprocessor supervisor circuits)
  Power_Supervisor.dcm
  Power_Supervisor.lib
Labels: Addition

#2248 Fix SG-8002LB pinname
  Oscillator.dcm
  Oscillator.lib
Labels: Bug, Enhancement, Pending reviewer

#2228 Adding JK0654219NL
  Connector.dcm
  Connector.lib
Labels: Addition, Pending changes

#2261 Update datasheet links for MCU_Microchip_SAME parts
  MCU_Microchip_SAME.dcm
Labels: Enhancement, Pending reviewer

#1661 Added TI SimpleLink CC1312r
  MCU_Texas_SimpleLink.dcm
  MCU_Texas_SimpleLink.lib
  sym-lib-table
Labels: Addition, Pending footprint

#2268 Fix Lattice ICE40HX4K-TQ144 VCC_SPI pin direction
  FPGA_Lattice.lib
Labels: Bug, Enhancement, Pending reviewer

#2272 Fix ADTxx descriptions
  Transformer.dcm
Labels: Enhancement, Pending reviewer

#2270 Microchip SAM E and SAM L corrections
  MCU_Microchip_SAME.lib
  MCU_Microchip_SAML.lib
Labels: Enhancement

#2252 Add INA233 as an alias of INA226.
  Analog_ADC.dcm
  Analog_ADC.lib
Labels: Addition

#1996 Add NCP1203 and NCP1217[A] as ALIASes
  Regulator_Controller.dcm
  Regulator_Controller.lib
Labels: Addition

#2271 Improve some sensor keywords and descriptions
  Sensor.dcm
Labels: Enhancement, Ready for review

#2273 Added SiSS27DN transistor, based on already existing Sis415DNT definition.
  Transistor_FET.dcm
  Transistor_FET.lib
Labels: Addition, Pending reviewer
