Repository KiCad/kicad-symbols, pull requests merged in 2019-05, with the labels that each got.

#819 - Created library MCU_Renesas_Synergy_S1
  MCU_Renesas_Synergy_S1.dcm
  MCU_Renesas_Synergy_S1.lib
  sym-lib-table
Labels: Addition, Pending changes

#1740 PIC18F87K22-I/PT Addition of symbol
  MCU_Microchip_PIC18.dcm
  MCU_Microchip_PIC18.lib
Labels: Addition

#906 PIC32MX795F512L added.
  MCU_Microchip_PIC32.dcm
  MCU_Microchip_PIC32.lib
Labels: Addition

#1803 74LS374 : Adding alias and fixing pins offset
  74xx.dcm
  74xx.lib
Labels: Addition, Enhancement

#1807 new zener diodes: DZ2SXXXX0L as alias of MM5Zxx
  Diode.dcm
  Diode.lib
Labels: Addition

#1806 MPL115A1: Change footprint
  Sensor_Pressure.lib
Labels: Enhancement

#1716 Add LMZ13608
  Regulator_Switching.dcm
  Regulator_Switching.lib
Labels: Addition

#1810 new schottky diode NSR0340HT1G
  Diode.dcm
  Diode.lib
Labels: Addition

#1749 AD8015 transimpedance amplifier, in SOIC-8
  Amplifier_Operational.dcm
  Amplifier_Operational.lib
Labels: Addition

#1794 add IR26-21C_L110_TR8
  LED.dcm
  LED.lib
Labels: Addition

#1813 add LT3045 voltage regulator, MSOP-12
  Regulator_Linear.dcm
  Regulator_Linear.lib
Labels: Addition

#1818 74LS04 : remove duplicate symbol, adding alias and fixing pin offset
  74xx.dcm
  74xx.lib
Labels: Addition, Enhancement, Pending reviewer

#1817 74LS273 : adding alias and fixing pin offset to 20mils
  74xx.dcm
  74xx.lib
Labels: Addition, Enhancement, Pending reviewer

#1781 Add TAS5825M
  Amplifier_Audio.dcm
  Amplifier_Audio.lib
Labels: Addition

#1822 Added RCLAMP3328P
  Power_Protection.dcm
  Power_Protection.lib
Labels: Addition

#1827 Added OPA551/OPA552 (from #1154)
  Amplifier_Operational.dcm
  Amplifier_Operational.lib
Labels: Addition, Re-push

#1795 TC4421/2 added
  Driver_FET.dcm
  Driver_FET.lib
Labels: Addition

#838 Added symbol for cree CLS6B-FKW, QLS6A-FKW and QLS6B-FKW
  LED.dcm
  LED.lib
Labels: Addition

#1833 Add CTRIM_Small to Devices
  Device.dcm
  Device.lib
Labels: Addition

#1831 add BUF602 buffer amplifier, SOIC-8
  Amplifier_Buffer.dcm
  Amplifier_Buffer.lib
Labels: Addition

#1835 Fix 'Inductor' description.
  pspice.dcm
Labels: Enhancement, Pending reviewer

#1830 Adding TMC2130-LA (from #866)
  Driver_Motor.dcm
  Driver_Motor.lib
Labels: Addition, Re-push

#1836 Add 74HC(T)1/237
  74xx.dcm
  74xx.lib
Labels: Addition

#1832 Adding TMC2130-TA (from #873)
  Driver_Motor.dcm
  Driver_Motor.lib
Labels: Addition, Re-push

#1166 add TPS22917 power switch from TI
  Power_Management.dcm
  Power_Management.lib
Labels: Addition

#1829 Interface_UART: Add ISO1500
  Interface_UART.dcm
  Interface_UART.lib
Labels: Addition

#1849 Transistor FET: Add Si7450DP as alias of Si7336ADP
  Transistor_FET.dcm
  Transistor_FET.lib
Labels: Addition, Enhancement, Re-push

#1842 Add UCC39002
  Power_Management.dcm
  Power_Management.lib
Labels: Addition

#1863 Small fix in ublox SAM
  RF_GPS.lib
Labels: Enhancement, Pending reviewer

#1860 Device: Add a new generic ABRG led
  Device.dcm
  Device.lib
Labels: Addition

#1646 ADD LM5050-1 And LM5050-2
  Power_Management.dcm
  Power_Management.lib
Labels: Addition

#1864 Add Silicon Labs microcontroller - EFM32G230F128G-E-QFN64
  MCU_SiliconLabs.dcm
  MCU_SiliconLabs.lib
Labels: Addition

#1862 Add ublox NEO-M8P
  RF_GPS.dcm
  RF_GPS.lib
Labels: Addition

#1839 Add OPA167x and MCP6401
  Amplifier_Operational.dcm
  Amplifier_Operational.lib
Labels: Addition

#1079 added ECS-2520MV-xxx-xx
  Oscillator.dcm
  Oscillator.lib
Labels: Addition

#1873 update MIC2026
  Power_Management.dcm
  Power_Management.lib
Labels: Enhancement

#1890 Small improve in INA226
  Analog_ADC.dcm
  Analog_ADC.lib
Labels: Enhancement

#1885 ADD INA219 SOIC and SOT-23
  Analog_ADC.dcm
  Analog_ADC.lib
Labels: Addition

#1869 ADD TPS2412
  Power_Management.dcm
  Power_Management.lib
Labels: Addition

#1880 Bugfix swapped RX and TX Pins of NXP Transceivers
  Interface_CAN_LIN.dcm
  Interface_CAN_LIN.lib
Labels: Bug

#1895 MCU_Microchip_SAMD: Fix line endings to Unix-style
  MCU_Microchip_SAMD.dcm
  MCU_Microchip_SAMD.lib
Labels: Enhancement, Pending reviewer

#1894 Is31fl3733
  Driver_LED.dcm
  Driver_LED.lib
Labels: Addition

#1854 LM26480: Dual 2MHz/1.5A buck converters + dual 300mA LDOs.
  Regulator_Switching.dcm
  Regulator_Switching.lib
Labels: Addition

#1891 Add MCP120/MCP130 supervisory family
  Power_Supervisor.dcm
  Power_Supervisor.lib
Labels: Addition

#1879 Add LTC4412
  Power_Management.dcm
  Power_Management.lib
Labels: Addition
