Repository KiCad/kicad-symbols, pull requests merged in 2020-01, with the labels that each got.

#2088 add Rohm LDO regulators in HTSOP-8 package
  Regulator_Linear.dcm
  Regulator_Linear.lib
Labels: Addition

#2114 add LTC1562 quad active RC-filter in SSOP-20
  Filter.dcm
  Filter.lib
Labels: Addition

#2420 Split FT232H into FT2232HL/FT2232HQ
  Interface_USB.dcm
  Interface_USB.lib
Labels: Bug

#2301 Change D & LED line thickness to 10mil
  Device.lib
  Diode.lib
  LED.lib
Labels: Enhancement

#2287 Add SHTC1, SHTC3
  Sensor_Humidity.dcm
  Sensor_Humidity.lib
Labels: Addition

#2409 Transistor_FET: Add alias of BUZ11 - VNP10N07
  Transistor_FET.dcm
  Transistor_FET.lib
Labels: Addition, Pending reviewer

#2177 Added NCS20071, NCS20072 and NCS20074
  Amplifier_Operational.dcm
  Amplifier_Operational.lib
Labels: Addition

#2429 Make 555 timers fully specified
  Timer.dcm
  Timer.lib
Labels: Enhancement, Pending reviewer

#2405 Add OPA858, OPA859, and OPA855 high-speed opamps, WSON-8
  Amplifier_Operational.dcm
  Amplifier_Operational.lib
Labels: Addition

#2423 Correct FP for SKY13575-639LF (point to manufacturer specific)
  RF_Switch.lib
Labels: Bug, Pending reviewer

#1866 Add Microchip ATSAMA5D21, 196-pin BGA Linux-capable MPU
  MCU_Microchip_SAMA.dcm
  MCU_Microchip_SAMA.lib
  sym-lib-table
Labels: Addition

#2070 Add SSM2211
  Amplifier_Audio.dcm
  Amplifier_Audio.lib
Labels: Addition, Pending changes

#2445 Oscillator: add LTC6905-XXX
  Oscillator.dcm
  Oscillator.lib
Labels: Addition, Pending changes

#2407 DRV8662: fixed pin length and stacked pins to avoid ERC error
  Driver_Motor.lib
Labels: Enhancement

#2404 Add NCR401U
  Driver_LED.dcm
  Driver_LED.lib
Labels: Addition, Pending changes

#1943 Add KSZ9563
  Interface_Ethernet.dcm
  Interface_Ethernet.lib
Labels: Addition

#858 Added PIC18F2420
  MCU_Microchip_PIC18.dcm
  MCU_Microchip_PIC18.lib
Labels: Addition, Pending changes

#2433 Fix LM319 'ground' pin type
  Comparator.dcm
  Comparator.lib
Labels: Bug

#2434 Fix UC3842 Vref pin type and name
  Regulator_Controller.lib
Labels: Bug

#2334 Add D3V3XA4B10LP Symbol
  Power_Protection.dcm
  Power_Protection.lib
Labels: Addition

#2299 Add DRV2605L
  Driver_Haptic.dcm
  Driver_Haptic.lib
Labels: Addition

#2443 Sensor_Temperature: add TC1047
  Sensor_Temperature.dcm
  Sensor_Temperature.lib
Labels: Addition, Pending changes

#2459 Fix simulation DIODE and OPAMP primitive types
  Simulation_SPICE.lib
Labels: Bug

#2285 Tps6303x
  Regulator_Switching.dcm
  Regulator_Switching.lib
Labels: Addition, Pending footprint

#2472 Corrected package for TPD3E001DRLR from SOT-543 to SOT-553
  Power_Protection.lib
Labels: Bug
