Repository KiCad/kicad-symbols, pull requests merged in 2020-05, with the labels that each got.

#2398 Add AS5047D Magnetic Position Sensor
  Sensor_Magnetic.dcm
  Sensor_Magnetic.lib
Labels: Addition

#2686 Power Management: Create TPS2663x devices
  Power_Management.dcm
  Power_Management.lib
Labels: Addition

#2693 BUF602 in SOT23-5
  Amplifier_Buffer.dcm
  Amplifier_Buffer.lib
Labels: Addition, Pending changes

#2559 Add MAX17620 switching voltage regulator.
  Regulator_Switching.dcm
  Regulator_Switching.lib
Labels: Addition

#2617 Added TPA6132A2RTE DirectPath stereo audio amplifier
  Amplifier_Audio.dcm
  Amplifier_Audio.lib
Labels: Addition

#2604 Mini-Circuits bandpass filter BPF-A355
  RF_Filter.dcm
  RF_Filter.lib
Labels: Addition

#2683 Add ADP2360
  Regulator_Switching.dcm
  Regulator_Switching.lib
Labels: Addition

#2360 Addition of MAX17501 DC-DC Converter
  Regulator_Switching.dcm
  Regulator_Switching.lib
Labels: Addition

#2631 Add Kemet Ex2 Series Mechanical Relays
  Relay.dcm
  Relay.lib
Labels: Addition

#2701 74xx:74LS109: fix incorrect polarity on K input
  74xx.lib
Labels: Bug

#2682 Added LC709203FQH*
  Battery_Management.dcm
  Battery_Management.lib
Labels: Addition

#2702 Adding alias for 74LS688, and small refresh
  74xx.dcm
  74xx.lib
Labels: Addition, Enhancement

#2704 Add OPA2156xD OPA2156xDGK
  Amplifier_Operational.dcm
  Amplifier_Operational.lib
Labels: Addition, Pending changes

#2709 fix issue #2641
  Interface_UART.lib
Labels: Bug

#2707 Add LTC6228 and LTC6229 opamps
  Amplifier_Operational.dcm
  Amplifier_Operational.lib
Labels: Addition

#2316 Add SC16IS750/760xPW and SC16IS750/760xBS
  Interface_UART.dcm
  Interface_UART.lib
Labels: Addition, Pending changes

#2698 add HMC799 high-speed transimpedance amplifier
  Amplifier_Operational.dcm
  Amplifier_Operational.lib
Labels: Addition

#2539 Add single version of ltc6752 high speed comparator
  Comparator.dcm
  Comparator.lib
Labels: Addition

#2691 add op1177 operational amplifier
  Amplifier_Operational.dcm
  Amplifier_Operational.lib
Labels: Addition

#2703 Add TPS54202
  Regulator_Switching.dcm
  Regulator_Switching.lib
Labels: Addition, Re-push

#2630 Connector: Add JAE Nano SIM Card SF72S006
  Connector.dcm
  Connector.lib
Labels: Addition

#2718 Fix LTC6752xSC6 naming
  Comparator.dcm
  Comparator.lib
Labels: Bug

#2710 Fix 74LS24[014]
  74xx.dcm
  74xx.lib
  74xx_IEEE.dcm
  74xx_IEEE.lib
Labels: Bug, Enhancement

#2279 Fix Vishay-MBLS pin order
  Diode_Bridge.lib
Labels: Bug

#2203 Add FETs in new packages
  Transistor_FET.dcm
  Transistor_FET.lib
Labels: Addition

#2564 Added Microchip LAN7500-ABJZ
  Interface_Ethernet.dcm
  Interface_Ethernet.lib
Labels: Addition, Re-push

#2428 Added ADP5090
  Battery_Management.dcm
  Battery_Management.lib
Labels: Addition

#1843 Add new gate drivers
  Amplifier_Audio.dcm
  Amplifier_Audio.lib
  Driver_FET.dcm
  Driver_FET.lib
Labels: Addition

#2086 add LM3914V led driver
  Driver_LED.dcm
  Driver_LED.lib
Labels: Addition

#2152 REF02: add aliases for Analog REF01/REF02/REF03
  Reference_Voltage.dcm
  Reference_Voltage.lib
Labels: Addition

#1990 add HMC1099PM5E and HMP8500PM5E power amplifiers
  RF_Amplifier.dcm
  RF_Amplifier.lib
Labels: Addition

#2044 add ADL5904 RF power detector
  RF.dcm
  RF.lib
Labels: Addition

#2724 Added AP228x4xW5 aliases to AP21x1W power switches
  Power_Management.dcm
  Power_Management.lib
Labels: Addition

#2708 Add LTC6752 family of comparators
  Comparator.dcm
  Comparator.lib
Labels: Addition, Pending changes

#2728 MOSFET IPB180N10S4-02
  Transistor_FET.dcm
  Transistor_FET.lib
Labels: Addition

#2726 ADM3057E isolated CAN transceiver
  Interface_CAN_LIN.dcm
  Interface_CAN_LIN.lib
Labels: Addition

#2658 Added Microchip PIC18F2xK22-xSO microcontrollers.
  MCU_Microchip_PIC18.dcm
  MCU_Microchip_PIC18.lib
Labels: Addition

#2741 Remove LS09 alias from LS08, and change output of LS09 to open collector
  74xx.lib
Labels: Bug

#2744 Add AO3400A as alias
  Transistor_FET.dcm
  Transistor_FET.lib
Labels: Addition

#2722 Add BAS19
  Diode.dcm
  Diode.lib
Labels: Addition

#1941 Split IRS2092 symbol by package
  Amplifier_Audio.dcm
  Amplifier_Audio.lib
Labels: Addition, Enhancement

#2752 Update MCU_Module.dcm
  MCU_Module.dcm
Labels: Bug

#2747 add BQ76200
  Battery_Management.dcm
  Battery_Management.lib
Labels: Addition

#2750 Add PAC193x QFN
  Analog_ADC.dcm
  Analog_ADC.lib
Labels: Addition

#2719 Add alias for tps56339
  Regulator_Switching.dcm
  Regulator_Switching.lib
Labels: Addition

#2373 Added symbol for Vl53l1x ToF distance sensor
  Sensor_Distance.dcm
  Sensor_Distance.lib
  sym-lib-table
Labels: Addition

#2759 Fix coupled inductors
  Device.lib
Labels: Bug, Pending reviewer

#2753 Add HIP4082
  Driver_FET.dcm
  Driver_FET.lib
Labels: Addition

#2419 Adding USB3250 UTMI PHY
  Interface_USB.dcm
  Interface_USB.lib
Labels: Addition

#2648 Added MAX4820 and MAX4821 relay drivers from Maxim Integrated
  Driver_Relay.dcm
  Driver_Relay.lib
Labels: Addition
