Repository KiCad/kicad-symbols, pull requests merged in 2020-08, with the labels that each got.

#2340 New symbol for FDMT MOSFET series
  Transistor_FET.dcm
  Transistor_FET.lib
Labels: Addition

#2893 Added schematic symbol for MIC4684
  Regulator_Switching.dcm
  Regulator_Switching.lib
Labels: Addition

#2848 Update Switch.lib
  Switch.dcm
  Switch.lib
Labels: Addition

#2669 Clean up Comparator lib, act two
  Comparator.dcm
  Comparator.lib
Labels: Enhancement

#2872 Regulator_Linear/AP2204K-1.5: move NC pin to the symbol outline
  Regulator_Linear.lib
Labels: Bug, Pending reviewer

#2866 Fix wrong footprint of Finder 32.21.x000
  Relay.lib
Labels: Bug, Pending reviewer

#2871 added aliases for OPA365
  Amplifier_Operational.dcm
  Amplifier_Operational.lib
Labels: Addition

#2873 Add SHT3x-DIS digital humidity sensors
  Sensor_Humidity.dcm
  Sensor_Humidity.lib
Labels: Addition, Re-push

#2851 Adding LM22678TJ-5, LM22678TJ-ADJ regulator
  Regulator_Switching.dcm
  Regulator_Switching.lib
Labels: Addition

#2889 Add AZ1084 5A LDO regulator
  Regulator_Linear.dcm
  Regulator_Linear.lib
Labels: Addition

#2755 Add N-MOS - Vishay SiS454DN
  Transistor_FET.dcm
  Transistor_FET.lib
Labels: Addition

#2896 Add MCP1802x-1202xOT
  Regulator_Linear.dcm
  Regulator_Linear.lib
Labels: Addition, Pending changes

#2819 Added Three-phase diode rectifiers
  Diode_Bridge.dcm
  Diode_Bridge.lib
Labels: Addition

#2888 Add Lattice iCE5LP1K-SG48 FPGA
  FPGA_Lattice.dcm
  FPGA_Lattice.lib
Labels: Addition, Pending reviewer

#2245 Adding AS4C256M16D3 DDR3 memory
  Memory_RAM.dcm
  Memory_RAM.lib
Labels: Addition

#2903 issue-2895 correcting fairchildsemi.com dead links
  4xxx.dcm
  Analog_Switch.dcm
  Driver_FET.dcm
  Isolator.dcm
  Regulator_Linear.dcm
  Regulator_Switching.dcm
  Relay_SolidState.dcm
  Transistor_BJT.dcm
  Transistor_FET.dcm
Labels: Enhancement

#2845 AP63200/AP63201/AP63203/AP63205
  Regulator_Switching.dcm
  Regulator_Switching.lib
Labels: Addition, Pending changes

#2814 Add TCMT4100 ond TCMT4106 optocoupler
  Isolator.dcm
  Isolator.lib
Labels: Addition, Pending changes

#2757 add LTC4151 - MSOP-10
  Analog_ADC.dcm
  Analog_ADC.lib
Labels: Addition

#2361 Addition of MAX15012 & MAX15013 Half Bridge Drivers
  Driver_FET.dcm
  Driver_FET.lib
Labels: Addition

#2786 Ade7763
  Sensor.dcm
  Sensor.lib
Labels: Addition, Enhancement

#2899 Added FL51x0MX
  Driver_FET.dcm
  Driver_FET.lib
Labels: Addition

#2906 Iso7763
  Isolator.dcm
  Isolator.lib
Labels: Addition

#2745 Add TI BQ76920/BQ76930
  Battery_Management.dcm
  Battery_Management.lib
Labels: Addition

#2891 Dmg9926 udm
  Transistor_FET.dcm
  Transistor_FET.lib
Labels: Addition

#2292 added Arduino Nano Every
  MCU_Module.dcm
  MCU_Module.lib
Labels: Addition

#2756 Add LP5912 symbol
  Regulator_Linear.dcm
  Regulator_Linear.lib
Labels: Addition, Pending changes

#2033 Add PSoC 4200M series (64-TQFP package)
  MCU_Cypress.dcm
  MCU_Cypress.lib
Labels: Addition

#2917 Added BSP75N self-protected FET
  Driver_FET.dcm
  Driver_FET.lib
Labels: Addition

#2835 Bugfix: fix position of VZCR pin on ACS730 (and aliases)
  Sensor_Current.lib
Labels: Bug

#2841 Added new mosfet. FDN340P
  Transistor_FET.dcm
  Transistor_FET.lib
Labels: Addition, Pending reviewer

#2830 Added THS5641A
  Analog_DAC.dcm
  Analog_DAC.lib
Labels: Addition

#2874 Added STGAP1AS
  Driver_FET.dcm
  Driver_FET.lib
Labels: Addition

#2908 Added Wuerth_750315371
  Transformer.dcm
  Transformer.lib
Labels: Addition

#2482 Add LA1185 FM mixer/receiver/amplifier chip from Sanyo
  RF_AM_FM.dcm
  RF_AM_FM.lib
Labels: Addition

#2877 Added L6491 Driver
  Driver_FET.dcm
  Driver_FET.lib
Labels: Addition

#2928 Removed coil polarity mark on G5V-1 symbol.
  Relay.lib
Labels: Bug

#2894 Added IRLML6401
  Transistor_FET.dcm
  Transistor_FET.lib
Labels: Addition, Enhancement

#2842 Added LM7171
  Amplifier_Operational.dcm
  Amplifier_Operational.lib
Labels: Addition

#2923 Ma8601
  Interface_USB.dcm
  Interface_USB.lib
Labels: Addition

#2915 Add Flash Memory GD25DxxCT
  Memory_Flash.dcm
  Memory_Flash.lib
Labels: Addition

#2846 Added IRM-60-5 with aliases.
  Converter_ACDC.dcm
  Converter_ACDC.lib
Labels: Addition, Pending changes

#2930 Add deprecation warning to README.md
  README.md
Labels: Enhancement, Librarian, Pending reviewer

#2746 Add Rohm EMH3, IMH3A and UMH3N dual NPN transistors
  Transistor_BJT.dcm
  Transistor_BJT.lib
Labels: Addition, Bug

#2875 Added MCP14AXXXXxMNY Drivers
  Driver_FET.dcm
  Driver_FET.lib
Labels: Addition

#2878 Added IR2x3x & IR2x3xS Drivers
  Driver_FET.dcm
  Driver_FET.lib
Labels: Addition

#604 add line transformer Macom ETC1-1-13
  Transformer.dcm
  Transformer.lib
Labels: Addition

#2085 add RF switch MASWSS0178
  RF_Switch.dcm
  RF_Switch.lib
Labels: Addition

#2007 add ADCH-80[A] RF chokes
  RF.dcm
  RF.lib
Labels: Addition

#2861 add STGP7NC60HD
  Transistor_IGBT.dcm
  Transistor_IGBT.lib
Labels: Addition

#2047 add MAX16050/MAX16051 voltage monitors/sequencer
  Power_Supervisor.dcm
  Power_Supervisor.lib
Labels: Addition

#2931 Add LM5164
  Regulator_Switching.dcm
  Regulator_Switching.lib
Labels: Addition

#2857 Add ADG884 analog switch
  Analog_Switch.dcm
  Analog_Switch.lib
Labels: Addition

#2715 Tps65130rge
  Regulator_Switching.dcm
  Regulator_Switching.lib
Labels: Addition

#2898 Adedd nRF52820
  MCU_Nordic.dcm
  MCU_Nordic.lib
Labels: Addition

#2934 Interface_CAN_LIN Fixes
  Interface_CAN_LIN.dcm
  Interface_CAN_LIN.lib
Labels: Bug, Enhancement

#2933 Add MCP1643 LED driver
  Driver_LED.dcm
  Driver_LED.lib
Labels: Addition

#2937 Added BL0937 - Energy Meter IC
  Sensor.dcm
  Sensor.lib
Labels: Addition

#2721 Add IS31AP4991 audio power amplifier
  Amplifier_Audio.dcm
  Amplifier_Audio.lib
Labels: Addition, Pending changes

#2944 Sn74 lv1 t34
  Logic_LevelTranslator.dcm
  Logic_LevelTranslator.lib
Labels: Addition

#2690 Add ADA4940-1ACPZ
  Amplifier_Difference.dcm
  Amplifier_Difference.lib
Labels: Addition

#2897 ADE7953 symbol
  Sensor.dcm
  Sensor.lib
Labels: Addition

#2815 Add MAX17263 Fuel Gauge symbol
  Battery_Management.dcm
  Battery_Management.lib
Labels: Addition

#2727 Add DIO6970 24V Buck Converter
  Regulator_Switching.dcm
  Regulator_Switching.lib
Labels: Addition

#2716 Tps61230drc
  Regulator_Switching.dcm
  Regulator_Switching.lib
Labels: Addition

#2949 Add Western Digital WD2791/WD2793/WD2795/WD2797 floppy disk controllers
  Interface.dcm
  Interface.lib
Labels: Addition

#2291 Added symbols for LEM CKSR series
  Sensor_Current.dcm
  Sensor_Current.lib
Labels: Addition

#2938 Added π120U30 and π120U31
  Isolator.dcm
  Isolator.lib
Labels: Addition
