Repository KiCad/kicad-symbols, pull requests merged in 2020-09, with the labels that each got.

#1735 Regulator_Linear: Rename variants of MCP1754 to follow naming convention
  Regulator_Linear.dcm
  Regulator_Linear.lib
Labels: Enhancement, Re-push

#1751 Move CH376 from Memory_Controller to to Interface
  Interface.dcm
  Interface.lib
  Memory_Controller.dcm
  Memory_Controller.lib
  sym-lib-table
Labels: Enhancement, Re-push

#2346 Align FE310-G000 with KLC, add FE310-G002 alias
  MCU_SiFive.dcm
  MCU_SiFive.lib
Labels: Enhancement

#2609 Remove ATSAMD21G18A-AUT
  MCU_Microchip_SAMD.dcm
  MCU_Microchip_SAMD.lib
Labels: Enhancement

#2782 74xx123: fix location of RCext and Cext
  74xx.lib
Labels: Enhancement

#2689 ADL5801: rearrange pins for more logical interface
  RF_Mixer.lib
Labels: Enhancement

#2615 Clear STM8 library
  MCU_ST_STM8.dcm
  MCU_ST_STM8.lib
Labels: Enhancement

#2929 Removed obsolete RF9394/5M
  Transistor_FET.dcm
  Transistor_FET.lib
Labels: Enhancement

#2880 Re-Push of ADuM764x
  Isolator.dcm
  Isolator.lib
Labels: Addition, Re-push

#2854 Fixing XC2C256-VQ100 symbol info/visual
  FPGA_Xilinx.dcm
  FPGA_Xilinx.lib
Labels: Enhancement

#2789 New valve set
  Valve.dcm
  Valve.lib
  Valve_Legacy.dcm
  Valve_Legacy.lib
  Valve_Modern.dcm
  Valve_Modern.lib
Labels: Addition

#1916 Added : Ai-Thinker-Ra-02 Module. Updated : Ai-Thinker-Ra-01 Module
  RF_Module.dcm
  RF_Module.lib
Labels: Addition, Enhancement

#1955 Fix timing capacitor pin naming of 4538
  4xxx.lib
Labels: Enhancement

#1855 Add PIC16F1619 devices to MCU_MicrochipPIC16
  MCU_Microchip_PIC16.dcm
  MCU_Microchip_PIC16.lib
Labels: Addition, Enhancement

#1932 HT12D
  Interface.dcm
  Interface.lib
Labels: Addition

#2626 Remove LM317-3PinPackage
  Regulator_Linear.dcm
  Regulator_Linear.lib
Labels: Enhancement

#1908 Update BQ24075
  Battery_Management.dcm
  Battery_Management.lib
Labels: Enhancement

#2706 add PAM8403DR, 3w stereo class d amp
  Amplifier_Audio.dcm
  Amplifier_Audio.lib
Labels: Addition

#2101 Added Vishay oled 128x64 symbol
  Display_Graphic.dcm
  Display_Graphic.lib
Labels: Addition

#2791 Add Linear LTC2451 16-bit ADC
  Analog_ADC.dcm
  Analog_ADC.lib
Labels: Addition

#2733 Add Toshiba 74VHC9164FT universal shift register
  74xx.dcm
  74xx.lib
Labels: Addition

#2796 Add Texas Instruments LM5023, QR PWM controller for off-line supplies
  Regulator_Controller.dcm
  Regulator_Controller.lib
Labels: Addition

#2822 Add MCP6V67EMNY Op Amp in TDFN-8
  Amplifier_Operational.dcm
  Amplifier_Operational.lib
Labels: Addition

#2006 move ADE-6 to RF_Mixer and add ADEX-10 alias
  RF.dcm
  RF.lib
  RF_Mixer.dcm
  RF_Mixer.lib
Labels: Addition, Enhancement

#2009 add RF switch HCM849A
  RF_Switch.dcm
  RF_Switch.lib
Labels: Addition

#2942 Added BSD235C Complementary P+N MOSFET.
  Transistor_FET.dcm
  Transistor_FET.lib
Labels: Addition

#2947 Add Motorola MC6802 symbol, with aliases for the MC68A02 and MC68B02
  CPU_NXP_6800.dcm
  CPU_NXP_6800.lib
Labels: Addition

#2961 Add SN74LV4T125 quad buffer as alias for 74LVC125
  74xx.dcm
  74xx.lib
Labels: Addition

#2955 Add Q_DUAL_NMOS_S1G1S2G2D2D2D1D1
  Device.dcm
  Device.lib
Labels: Addition

#2869 Add SGL0622Z RF Amplifier
  RF_Amplifier.dcm
  RF_Amplifier.lib
Labels: Addition

#2957 Added HT12E
  Interface.dcm
  Interface.lib
Labels: Addition

#2660 add l7980 switching regulator
  Regulator_Switching.dcm
  Regulator_Switching.lib
Labels: Addition

#2364 CP2102N: Fix double-negated pins, add QFN20 symbol
  Interface_USB.dcm
  Interface_USB.lib
Labels: Addition

#2912 Correct pin types for DWM1000 and fix a few for DWM1001
  RF_Module.lib
Labels: Enhancement

#2632 Add dual diodes in two new symbol styles
  Device.dcm
  Device.lib
Labels: Addition

#2941 Added AP3402 buck converter
  Regulator_Switching.dcm
  Regulator_Switching.lib
Labels: Addition

#2956 Added TMP1075 temperature sensors family
  Sensor_Temperature.dcm
  Sensor_Temperature.lib
Labels: Addition

#2804 Added EFM8UB3 Devices
  MCU_SiliconLabs.dcm
  MCU_SiliconLabs.lib
Labels: Addition

#2969 Commonalize CP2104
  Interface_USB.dcm
  Interface_USB.lib
Labels: Enhancement, garlic

#2904 add further sources to pspice symbols
  pspice.dcm
  pspice.lib
Labels: Addition

#2596 Added DA14691 and DA14695
  MCU_Dialog.dcm
  MCU_Dialog.lib
  sym-lib-table
Labels: Addition, Pending footprint

#2566 Add PCA9557 I2C GPIO expander.
  Interface_Expansion.dcm
  Interface_Expansion.lib
Labels: Addition

#2802 Add Onsemi MDBxxS, Bridge Rectifiers
  Diode_Bridge.dcm
  Diode_Bridge.lib
Labels: Addition

#2801 Add Schaffner RN102 series common mode chokes
  Filter.dcm
  Filter.lib
Labels: Addition

#2821 Add LT1461 voltage reference in SOIC-8
  Reference_Voltage.dcm
  Reference_Voltage.lib
Labels: Addition

#2021 Add Atmel_ATSAMR21G18-MR210UA_NoRFPads
  RF_Module.dcm
  RF_Module.lib
Labels: Addition

#2712 Added BQ24230 (based on pull request #2417).
  Power_Management.dcm
  Power_Management.lib
Labels: Addition, Re-push

#2950 Revert dual output audio amps
  Amplifier_Audio.lib
  Sensor_Magnetic.dcm
  Sensor_Magnetic.lib
Labels: Enhancement

#2729 Add UCC256301
  Regulator_Controller.dcm
  Regulator_Controller.lib
Labels: Addition

#2676 dsPIC33EP256MU810 Addition
  DSP_Microchip_DSPIC33.dcm
  DSP_Microchip_DSPIC33.lib
Labels: Addition

#2777 Add Senseair S8 family CO2 sensors
  Sensor_Gas.dcm
  Sensor_Gas.lib
Labels: Addition

#2309 Added 74XG123
  74xGxx.dcm
  74xGxx.lib
Labels: Enhancement

#2960 Added TFA9879xx to Amplifier_Audio.lib
  Amplifier_Audio.dcm
  Amplifier_Audio.lib
Labels: Addition

#2688 Add TLV320AIC3100 Audio Codec
  Audio.dcm
  Audio.lib
Labels: Addition

#2945 Added symbol TPSM53602RDAR and aliases
  Converter_DCDC.dcm
  Converter_DCDC.lib
Labels: Addition

#2883 Added PIC32MK1024GPX100 serie
  MCU_Microchip_PIC32.dcm
  MCU_Microchip_PIC32.lib
Labels: Addition

#2921 Added new simbol library
  Interface_UART.dcm
  Interface_UART.lib
Labels: Addition

#2865 Ice40UL1K-16WCLSP
  FPGA_Lattice.dcm
  FPGA_Lattice.lib
Labels: Addition, Pending footprint

#1985 Add ICE40HX4K-BG121 alias
  FPGA_Lattice.dcm
  FPGA_Lattice.lib
Labels: Addition, Pending changes

#2974 Move MCP7940 into Timer_RTC
  Timer.dcm
  Timer.lib
  Timer_RTC.dcm
  Timer_RTC.lib
Labels: Bug, garlic

#2959 add LED1642GW
  Driver_LED.dcm
  Driver_LED.lib
Labels: Addition

#2783 Add Microchip MCP1501 family voltage reference
  Reference_Voltage.dcm
  Reference_Voltage.lib
Labels: Addition

#2374 Add LP38512 series
  Regulator_Linear.dcm
  Regulator_Linear.lib
Labels: Addition

#2935 Create single- and double-row symbols
  Connector.dcm
  Connector.lib
Labels: Addition

#2684 trf37a73: stack no-connect pins to allow connecting to ground
  RF_Amplifier.lib
Labels: Enhancement

#1848 Add AMC1100/AMC1300
  Amplifier_Difference.dcm
  Amplifier_Difference.lib
Labels: Addition

#1650 Fix naming convention for Device.lib
  Device.dcm
  Device.lib
Labels: Enhancement

#1703 Adding Samtec ASP-134486-01 connector (ASP-134602-01 alias)
  Connector.dcm
  Connector.lib
Labels: Addition

#2973 Update Murata NXE
  Regulator_Switching.dcm
  Regulator_Switching.lib
Labels: Enhancement, garlic

#2312 Adding MT48 256Mb SDRAM. Changing some old SDRAMs
  Memory_RAM.dcm
  Memory_RAM.lib
Labels: Addition, Enhancement

#2785 Fix the control outputs of 8288 for multi-master operation
  Interface.lib
Labels: Bug

#2655 Fix generic USB connector pin types
  Connector.lib
Labels: Bug, Enhancement

#2535 Add LTC6268-10 Opamp
  Amplifier_Operational.dcm
  Amplifier_Operational.lib
Labels: Addition

#2499 Gate drivers
  Driver_FET.dcm
  Driver_FET.lib
Labels: Addition

#2146 Fix Pin7 on ATSAME5x devices
  MCU_Microchip_SAME.lib
Labels: Bug

#2049 Add Texas Instruments TLV767 Low Dropout Fixed and Variable Linear Regulators
  Driver_Motor.dcm
  Driver_Motor.lib
  Regulator_Linear.dcm
  Regulator_Linear.lib
Labels: Addition

#2231 Add SRC4392 audio sample rate converter
  Audio.dcm
  Audio.lib
Labels: Addition

#2979 Remove old din41612 symbols
  Connector.dcm
  Connector.lib
Labels: garlic

#2886 Add symbol for NXP Kinetis MKW41Z, MKW31Z and MKW21Z MCUs
  MCU_NXP_Kinetis.dcm
  MCU_NXP_Kinetis.lib
Labels: Addition

#2980 More device lib naming
  Device.dcm
  Device.lib
Labels: Enhancement, garlic

#1651 Remove lead finish suffixes from Microchip AVR MCUs
  MCU_Microchip_8051.dcm
  MCU_Microchip_8051.lib
  MCU_Microchip_ATmega.dcm
  MCU_Microchip_ATmega.lib
  MCU_Microchip_ATtiny.dcm
  MCU_Microchip_ATtiny.lib
  MCU_Microchip_AVR.dcm
  MCU_Microchip_AVR.lib
Labels: Enhancement

#1148 Comparator: Add LM397 and TL331
  Comparator.dcm
  Comparator.lib
Labels: Abandoned, Addition

#2982 Move LTC4317 to Interface_Expansion
  Interface.dcm
  Interface.lib
  Interface_Expansion.dcm
  Interface_Expansion.lib
Labels: Bug, Enhancement, garlic

#2720 Add ltc6804 1
  Battery_Management.dcm
  Battery_Management.lib
Labels: Addition

#2335 Add LT4295 and LT4320/1
  Power_Management.dcm
  Power_Management.lib
  Regulator_Controller.dcm
  Regulator_Controller.lib
Labels: Addition

#2859 Add RAK Wireless RAK4200 LoRa module schematic symbol
  RF_Module.dcm
  RF_Module.lib
Labels: Addition

#2717 Bq24090dgq
  Battery_Management.dcm
  Battery_Management.lib
Labels: Addition

#2621 Si5342/44/45: Jitter Attenuators / Clock Multipliers.
  Timer_PLL.dcm
  Timer_PLL.lib
Labels: Addition

#2788 MCU_ST_STM32G0: Add STM32G071KxT / STM32G071KxU
  MCU_ST_STM32G0.dcm
  MCU_ST_STM32G0.lib
  sym-lib-table
Labels: Addition

#2952 Sensor_Audio: add Knowles SPH0641LU4H digital MEMS microphone
  Sensor_Audio.dcm
  Sensor_Audio.lib
Labels: Addition

#2954 Added Johanson 0900PC15J0013 balun
  RF.dcm
  RF.lib
Labels: Addition

#2812 Add RAK Wireles RAK811 LoRa module schematic symbol
  RF_Module.dcm
  RF_Module.lib
Labels: Addition

#2951 Add IS43LQ32256A-062BLI and alias IS43LQ32256AL-062BLI.
  Memory_RAM.dcm
  Memory_RAM.lib
Labels: Addition

#901 Added LM4132B to Reference Voltage
  Reference_Voltage.dcm
  Reference_Voltage.lib
Labels: Abandoned, Addition, Pending changes

#2039 Add LT1634 Voltage Reference
  Reference_Voltage.dcm
  Reference_Voltage.lib
Labels: Addition

#2399 Add Allegro A4954 H-Bridge
  Driver_Motor.dcm
  Driver_Motor.lib
Labels: Addition

#1964 Add MAX17261 symbol
  Battery_Management.dcm
  Battery_Management.lib
Labels: Addition

#2981 Adding PCB Edge PCI Express connectors
  Connector.dcm
  Connector.lib
Labels: Addition, garlic

#2259 Adding M.2 connectors (A, B, E, M Mechanical Keys)
  Connector.dcm
  Connector.lib
Labels: Addition

#2597 Add CC430F513xIRGZ
  MCU_Texas_MSP430.dcm
  MCU_Texas_MSP430.lib
Labels: Addition

#1947 add ADA4077-1 OpAmps
  Amplifier_Operational.dcm
  Amplifier_Operational.lib
Labels: Addition

#758 Bq76940
  Battery_Management.dcm
  Battery_Management.lib
Labels: Enhancement

#757 BQ78350
  Battery_Management.dcm
  Battery_Management.lib
Labels: Enhancement

#2202 add ADA4610 operational amplifiers
  Amplifier_Operational.dcm
  Amplifier_Operational.lib
Labels: Addition

#1733 add OPA569 high-current opamp in SO-20 PowerPAD
  Amplifier_Operational.dcm
  Amplifier_Operational.lib
Labels: Addition

#2463 Rename STM32L4x1 VDDUSB pin into VDD
  MCU_ST_STM32L4.lib
Labels: Enhancement

#3085 Ncp662
  Regulator_Linear.dcm
  Regulator_Linear.lib
Labels: Addition, Re-push, garlic

#2263 Add MAX941
  Comparator.dcm
  Comparator.lib
Labels: Addition

#2019 Add MS5525DSO Pressure-Sensor
  Sensor_Pressure.dcm
  Sensor_Pressure.lib
Labels: Addition

#2887 Add BM78 Class 2 Bluetooth/BLE module
  RF_Bluetooth.dcm
  RF_Bluetooth.lib
Labels: Addition

#2215 Add Nexperia PMEG SOT-1289 Schottky diodes
  Diode.dcm
  Diode.lib
Labels: Addition

#2600 Added Johanson CC11xx baluns, for 433, 868 and 915Mhz
  Transformer.dcm
  Transformer.lib
Labels: Addition

#2003 Add TPA3251
  Amplifier_Audio.dcm
  Amplifier_Audio.lib
Labels: Addition

#2230 add RJ45 LAN transformer Würth 74920111211
  Connector.dcm
  Connector.lib
Labels: Addition, Pending changes

#2884 Added PN512 RFID module
  RF_RFID.dcm
  RF_RFID.lib
Labels: Addition

#2758 add NXP PN532 NFC
  RF_NFC.dcm
  RF_NFC.lib
  sym-lib-table
Labels: Addition

#1548 Added LM199/399 voltage reference
  Reference_Voltage.dcm
  Reference_Voltage.lib
Labels: Addition, Pending footprint

#3086 Fix inconsistences between On Semi QRE1113/QRE1113GR and Everlight ITR8307/ITR1201SR10
  Sensor_Proximity.dcm
  Sensor_Proximity.lib
Labels: Bug, garlic

#2344 Fix pins for ADT1.5-1
  Transformer.dcm
  Transformer.lib
Labels: Bug, Enhancement

#3089 MCP9804_DFN fix package
  Sensor_Temperature.lib
Labels: Bug, garlic

#2017 PCM2902, ISD25xx added
  Audio.dcm
  Audio.lib
Labels: Addition

#2900 Added BZV55xxxx Zener Diode full list
  Diode.dcm
  Diode.lib
Labels: Addition

#2281 Bc95
  RF_GSM.dcm
  RF_GSM.lib
Labels: Addition

#2250 Adding LFE5UM5G-85F, LFE5UM-85F and LFE5U-85F in 381 and 756 pin packages
  FPGA_Lattice.dcm
  FPGA_Lattice.lib
Labels: Addition

#2692 Add AC/DC converter series: Recom RAC20-xxSK
  Converter_ACDC.dcm
  Converter_ACDC.lib
Labels: Addition

#2781 PIC32MM0064GPL028-xML adding new part
  MCU_Microchip_PIC32.dcm
  MCU_Microchip_PIC32.lib
Labels: Addition

#2962 Added EA DOGM128 and DOGL128 displays
  Display_Graphic.dcm
  Display_Graphic.lib
Labels: Addition

#3090 Add Recom RAC20-xxDK Dual Output Parts
  Converter_ACDC.dcm
  Converter_ACDC.lib
Labels: Addition, garlic

#2754 Add FT5HN and FT5HV
  Oscillator.dcm
  Oscillator.lib
Labels: Addition

#2513 Add Texas Instruments TS3DS10224
  Analog_Switch.dcm
  Analog_Switch.lib
Labels: Addition

#2711 Add RClamp0502B, RClamp0502BA and RClamp0582B
  Power_Protection.dcm
  Power_Protection.lib
Labels: Addition

#3092 Changed RAC pin names to exactly match the datasheet
  Converter_ACDC.lib
Labels: Enhancement, garlic

#3094 Make Texas_WSON-N8 variants non vendor specific
  Regulator_Linear.lib
Labels: Bug, Enhancement, garlic

#2852 OPA818 op-amp in 3x3mm WSON-8
  Amplifier_Operational.dcm
  Amplifier_Operational.lib
Labels: Addition

#2763 Added Adesto AT25SL321-UUE-T 32-Mbit FLASH memory
  Memory_Flash.dcm
  Memory_Flash.lib
Labels: Addition

#2508 Update footprint pointers for Murata based components
  Converter_DCDC.lib
  RF_Module.dcm
  Regulator_Switching.lib
Labels: Enhancement

#2590 Added MPR121QR2
  Sensor_Touch.dcm
  Sensor_Touch.lib
Labels: Addition

#2219 Add RB1-125B8G1A RJ45 jack
  Connector.dcm
  Connector.lib
Labels: Addition

#2351 Addition of INA333 Instrumentation Amplifer
  Amplifier_Instrumentation.dcm
  Amplifier_Instrumentation.lib
Labels: Addition, Pending footprint

#2593 Added AX−SIP−SFEU and AX−SIP−SFEU-API
  RF_Module.dcm
  RF_Module.lib
Labels: Addition

#1974 Add MMZ09332BT1 symbol
  RF_Amplifier.dcm
  RF_Amplifier.lib
Labels: Addition

#1797 TMC5130-TA added
  Driver_Motor.dcm
  Driver_Motor.lib
Labels: Addition

#1811 TMC5160-TA added.
  Driver_Motor.dcm
  Driver_Motor.lib
Labels: Addition, Re-push

#2910 Add Rayac MDBT50Q Module
  RF_Module.dcm
  RF_Module.lib
Labels: Addition

#2213 Add Nexperia PMEG SOD-123W Schottky diodes
  Diode.dcm
  Diode.lib
Labels: Addition

#2657 Add symbol for Quectel L80 GPS module
  RF_GPS.dcm
  RF_GPS.lib
Labels: Addition

#3096 Fix datasheets of LP2951-***
  Regulator_Linear.dcm
Labels: Bug, garlic

#2602 Add Panasonic AQ-H series solid state relays, DIP & SMD + zero cross & random
  Relay_SolidState.dcm
  Relay_SolidState.lib
Labels: Addition

#2533 Fix S5.1 and S5.2 errors in Timer.lib (#953)
  Timer.lib
Labels: Addition, Bug, Enhancement

#1587 Rename SOIJ-8 footprint to SOIC-8W
  MCU_Microchip_ATtiny.lib
  Memory_EEPROM.lib
  Memory_Flash.lib
  obsolete/MCU_Microchip_ATtiny.lib
  obsolete/MCU_Microchip_AVR.lib
Labels: Enhancement
