Repository KiCad/kicad-symbols, pull requests merged in 2020-02, with the labels that each got.

#2466 New comparators: LMV7219 and LTC6754 family
  Comparator.dcm
  Comparator.lib
Labels: Addition, Pending changes

#2454 Add TPS61040 variants
  Regulator_Switching.dcm
  Regulator_Switching.lib
Labels: Addition

#2104 Add MAX31865
  Sensor_Temperature.dcm
  Sensor_Temperature.lib
Labels: Addition, Pending footprint

#2453 Add ADM3488E/ADM3490E/ADM3491E RS-422/RS-485 transceivers
  Interface_UART.dcm
  Interface_UART.lib
Labels: Addition

#2461 Add TI LM2665 switching capacitor regulator
  Regulator_SwitchedCapacitor.dcm
  Regulator_SwitchedCapacitor.lib
Labels: Addition

#2441 Add Pericon PI6C5946002 1:2 6GHz/12Gbps CML Clock/Data Buffer
  Buffer.dcm
  Buffer.lib
  sym-lib-table
Labels: Addition

#2444 Regulator_Linear: add TC2014 LDO family
  Regulator_Linear.dcm
  Regulator_Linear.lib
Labels: Addition, Pending changes

#2485 Addition of lots of LT RS22/485 Drivers
  Interface_UART.dcm
  Interface_UART.lib
Labels: Addition

#2475 Add NHS3100
  MCU_NXP_NTAG.dcm
  MCU_NXP_NTAG.lib
  sym-lib-table
Labels: Addition

#2493 Added JTD15 and JTD20 series of DC-DC Converters from XP Power
  Converter_DCDC.dcm
  Converter_DCDC.lib
Labels: Addition, Pending changes

#2498 Fix permissions of Interface lib
  Interface.dcm
  Interface.lib
Labels: Bug

#2496 Added Recom RPA60 series of 60W DC-DC converters
  Converter_DCDC.dcm
  Converter_DCDC.lib
Labels: Addition

#1858 Add Ublox ZED F9P
  RF_GPS.dcm
  RF_GPS.lib
Labels: Addition

#2436 Added TPS782xx LDO family in SOT-23.
  Regulator_Linear.dcm
  Regulator_Linear.lib
Labels: Addition

#2004 Add ATX 20pins and 24 pins
  Connector.dcm
  Connector.lib
Labels: Addition, Pending changes
