Repository KiCad/kicad-symbols, pull requests merged in 2020-03, with the labels that each got.

#2516 Fix pin names on 74HC137
  74xx.lib
Labels: Bug

#2350 Add MAX14830
  Interface_UART.dcm
  Interface_UART.lib
Labels: Addition

#2522 Update typo in Voltage_Reference.dcm: "Prevision" -> "Precision"
  Reference_Voltage.dcm
Labels: Bug

#2497 Added PTN780x0 Series of DC-DC Converters from Texas Instruments
  Converter_DCDC.dcm
  Converter_DCDC.lib
Labels: Addition

#2310 added LTC3105
  Regulator_Switching.dcm
  Regulator_Switching.lib
Labels: Addition

#2526 Fix broken Converter_DCDC
  Converter_DCDC.dcm
  Converter_DCDC.lib
Labels: Bug

#2524 Added MCP9844 TWI temperature sensor.
  Sensor_Temperature.dcm
  Sensor_Temperature.lib
Labels: Addition

#1874 added nRF52811
  MCU_Nordic.dcm
  MCU_Nordic.lib
Labels: Addition

#2304 Adding MAX1112x ADCs
  Analog_ADC.dcm
  Analog_ADC.lib
Labels: Addition

#2531 Fixed 74LS295: OE input incorrectly marked as inverted
  74xx.lib
Labels: Bug

#2536 Add Alias for LTC6253xMS8 (Dual OpAmp)
  Amplifier_Operational.dcm
  Amplifier_Operational.lib
Labels: Addition

#1915 Relay: Add Panasonic ADW11 series
  Relay.dcm
  Relay.lib
Labels: Addition

#2470 Added PIC16(L)F15356/75/76/85/86 Symbols
  MCU_Microchip_PIC16.dcm
  MCU_Microchip_PIC16.lib
Labels: Addition

#2544 Added ADR45xx voltage reference family
  Reference_Voltage.dcm
  Reference_Voltage.lib
Labels: Addition

#2380 Add MCP4725
  Analog_DAC.dcm
  Analog_DAC.lib
Labels: Addition

#2186 Add TI DAC[5-7]578 DACs
  Analog_DAC.dcm
  Analog_DAC.lib
Labels: Addition

#2505 Add TS3L501E 8-channel mux
  Analog_Switch.dcm
  Analog_Switch.lib
Labels: Addition

#2528 Add LMR33640 swtching regulator
  Regulator_Switching.dcm
  Regulator_Switching.lib
Labels: Addition, Pending changes

#2352 Addition of LM20 Temperature Sensor
  Sensor_Temperature.dcm
  Sensor_Temperature.lib
Labels: Addition, Pending changes

#2523 Create Traco TDN 5 single supply
  Regulator_Switching.dcm
  Regulator_Switching.lib
Labels: Addition, Pending reviewer

#2545 Fix EFM8BB10F8G-A-QFN20 default FP
  MCU_SiliconLabs.lib
Labels: Bug, Pending footprint

#2515 Tlv9001v2
  Amplifier_Operational.dcm
  Amplifier_Operational.lib
Labels: Addition, Pending changes

#2541 Add TPS730 LDO voltage regulator
  Regulator_Linear.dcm
  Regulator_Linear.lib
Labels: Addition, Enhancement

#2555 Added LM5176 Buck-boost controller as alias of LM5175
  Regulator_Switching.dcm
  Regulator_Switching.lib
Labels: Addition

#2551 Add FAN7388 as alias of FAN7888
  Driver_FET.dcm
  Driver_FET.lib
Labels: Addition

#2550 Added US1x ultra fast recitier diodes family
  Diode.dcm
  Diode.lib
Labels: Addition

#2336 Add SAM D21 family
  MCU_Microchip_SAMD.dcm
  MCU_Microchip_SAMD.lib
Labels: Addition, Duplicate

#2560 LF351 symbol added
  Amplifier_Operational.dcm
  Amplifier_Operational.lib
Labels: Addition, Pending changes

#2347 Fix not-on-100mil-grid body for FU540-C000
  MCU_SiFive.lib
Labels: Enhancement

#2565 Changed pin to signal assignment for pins 9 to 12 according to the da…
  Analog_Switch.lib
Labels: Bug

#2558 Added coupled inductor symbols, with different pinout.
  Device.dcm
  Device.lib
Labels: Addition, Duplicate

#2561 Changed PCF8574 footprint filter, added a package variant
  Interface_Expansion.dcm
  Interface_Expansion.lib
Labels: Addition, Enhancement

#1725 Added Filter/0850BM14E0016
  Filter.dcm
  Filter.lib
Labels: Addition

#1782 Add LMR33630 switching regulator family in 8-pin HSOIC package
  Regulator_Switching.dcm
  Regulator_Switching.lib
Labels: Addition, Pending changes

#2375 Added ESD9B family of ESD TVS diodes.
  Diode.dcm
  Diode.lib
Labels: Addition

#2435 Added symbol for FDC6330L load switch.
  Transistor_FET.dcm
  Transistor_FET.lib
Labels: Addition

#2427 Add MCP2221A USB to I2C bridge components
  Interface_USB.dcm
  Interface_USB.lib
Labels: Addition

#2400 Add STM32H750 aliases
  MCU_ST_STM32H7.dcm
  MCU_ST_STM32H7.lib
Labels: Addition

#1796 Mpl3115a2
  Sensor_Pressure.dcm
  Sensor_Pressure.lib
Labels: Addition

#2376 Add coupled inductors with 1-3-4-2 pinout
  Device.dcm
  Device.lib
Labels: Addition

#2478 Added LAN8710A symbol
  Interface_Ethernet.dcm
  Interface_Ethernet.lib
Labels: Addition

#2569 Fix L_Core_xxxx_Coupled_1324 introduced in #2376
  Device.dcm
  Device.lib
Labels: Bug

#2159 Add CH340E
  Interface_USB.dcm
  Interface_USB.lib
Labels: Addition

#2408 Analog_ADC: Add ICL7106/7
  Analog_ADC.dcm
  Analog_ADC.lib
Labels: Addition

#2484 Add LM2931 low-drop voltage regulator in TO220 package
  Regulator_Linear.dcm
  Regulator_Linear.lib
Labels: Addition

#2452 Add nxe1 s0x0x mc
  Regulator_Switching.dcm
  Regulator_Switching.lib
Labels: Addition

#1847 Ltm4637
  Regulator_Switching.dcm
  Regulator_Switching.lib
Labels: Addition

#1954 Add Maxim DS1210 Nonvolatile Controller Chip
  Power_Management.dcm
  Power_Management.lib
Labels: Addition

#2297 Adding NXP PCA9306D
  Interface.dcm
  Interface.lib
Labels: Addition

#1857 Added 4009, 4010 Hex Buffers with separated VCC, VDD and high sink cu…
  4xxx.dcm
  4xxx.lib
Labels: Addition

#1841 Add Abracon ABx8x5 RTCs
  Timer_RTC.dcm
  Timer_RTC.lib
Labels: Addition

#2570 Add LM329
  Reference_Voltage.dcm
  Reference_Voltage.lib
Labels: Addition

#2582 Added UCC27714
  Driver_FET.dcm
  Driver_FET.lib
Labels: Addition

#2553 Added LM5161PWP
  Regulator_Switching.dcm
  Regulator_Switching.lib
Labels: Addition

#2532 Added ADS1220IPWR ADC
  Analog_ADC.dcm
  Analog_ADC.lib
Labels: Addition

#2580 Added UCCx895
  Regulator_Controller.dcm
  Regulator_Controller.lib
Labels: Addition

#2424 Adding StULPI01A, STULPI01B
  Interface_USB.dcm
  Interface_USB.lib
Labels: Addition

#2227 Adding TFP410
  Video.dcm
  Video.lib
Labels: Addition

#2518 BUS Mini-PCIe: Add MP pin
  Connector.lib
Labels: Enhancement

#2572 Addition of LM3150 Buck Converter Controller
  Regulator_Switching.dcm
  Regulator_Switching.lib
Labels: Addition

#2592 Add more generic ground symbols
  power.dcm
  power.lib
Labels: Addition

#2207 Adding 5P49V6965
  Oscillator.dcm
  Oscillator.lib
Labels: Addition

#2216 Adding TPD4E02B04
  Power_Protection.dcm
  Power_Protection.lib
Labels: Addition, Re-push

#2212 Adding CBTL02043A, CBTL02043B
  Analog_Switch.dcm
  Analog_Switch.lib
Labels: Addition
