Repository KiCad/kicad-symbols, pull requests merged in 2020-06, with the labels that each got.

#2760 Fix TPS562200 pins
  Regulator_Switching.lib
Labels: Enhancement

#2029 Add MC100LVELT22 and MC100EPT22 LVTTL to LVPECL level translators
  Interface.dcm
  Interface.lib
Labels: Addition

#2483 Add X02xxxN
  Triac_Thyristor.dcm
  Triac_Thyristor.lib
Labels: Addition

#2036 Add Texas Instruments TPS61322 series boost converters
  Regulator_Switching.dcm
  Regulator_Switching.lib
Labels: Addition

#2034 Add Diodes Incorporated PAM2301 series buck converters
  Regulator_Switching.dcm
  Regulator_Switching.lib
Labels: Addition

#2778 Add Microchip MCP6V67 as alias of LM2904
  Amplifier_Operational.dcm
  Amplifier_Operational.lib
Labels: Addition

#2776 Added LMR33620
  Regulator_Switching.dcm
  Regulator_Switching.lib
Labels: Addition

#2448 Added display NHD-C0220BiZ
  Display_Character.dcm
  Display_Character.lib
Labels: Addition, Re-push

#2775 Added LMR33610
  Regulator_Switching.dcm
  Regulator_Switching.lib
Labels: Addition

#1946 Add Infineon GaN FET symbols
  Transistor_FET.dcm
  Transistor_FET.lib
Labels: Addition, Pending footprint

#2406 RT9361AGE / BGE
  Regulator_SwitchedCapacitor.dcm
  Regulator_SwitchedCapacitor.lib
Labels: Addition

#2185 Add tps62056dgs step-down converter
  Regulator_Switching.dcm
  Regulator_Switching.lib
Labels: Addition

#2808 Add Broadcom ACPL-214-500E AC/DC optocoupler as alias of TLP290
  Isolator.dcm
  Isolator.lib
Labels: Addition

#2806 Add Nexperia BUK7880-55A, enhancement mode MOSFET as alias of BSP89
  Transistor_FET.dcm
  Transistor_FET.lib
Labels: Addition

#2790 Adding 74AHC240 74AHCT240 alias
  74xx.dcm
  74xx.lib
Labels: Addition

#2793 Clear IRMxx-xx family descriptions
  Converter_ACDC.dcm
  Converter_ACDC.lib
Labels: Addition, Enhancement, Pending reviewer

#2794 Add Nexperia 74HC165 8-bit as alias to 74LS165
  74xx.dcm
  74xx.lib
Labels: Addition

#2800 Add Comchip CDBA3xxx-HF series Schottky diodes as alias of B120-E3
  Diode.dcm
  Diode.lib
Labels: Addition

#2748 Add SiS443DN
  Transistor_FET.dcm
  Transistor_FET.lib
Labels: Addition

#2823 add diode to input side of LTV-814 to reflect AC input
  Isolator.dcm
  Isolator.lib
Labels: Enhancement
