Repository KiCad/kicad-symbols, pull requests merged in 2020-04, with the labels that each got.

#2480 Adding SN74LVC1G14 in SOT-23 and SC70 packages
  74xGxx.dcm
  74xGxx.lib
Labels: Addition

#2571 Add AD654
  Analog.dcm
  Analog.lib
Labels: Addition

#2121 add SN74LVC2T45YZP
  Logic_LevelTranslator.dcm
  Logic_LevelTranslator.lib
Labels: Addition

#2599 Add CH340C
  Interface_USB.dcm
  Interface_USB.lib
Labels: Addition, Re-push

#2181 Adding TPS6282xDLC
  Regulator_Switching.dcm
  Regulator_Switching.lib
Labels: Addition

#1856 USB334x - Enhanced Single Supply Hi-Speed USB ULPI Transceiver
  Interface_USB.dcm
  Interface_USB.lib
Labels: Addition

#2542 added TPS54061
  Regulator_Switching.dcm
  Regulator_Switching.lib
Labels: Addition

#1935 Murata MGJ2 Series (symbol)
  Converter_DCDC.dcm
  Converter_DCDC.lib
Labels: Addition

#2606 Fix 2 logic symbols
  74xx.lib
Labels: Bug

#2396 Interface: Add CP2615-A02 USB to I2S bridge
  Interface_USB.dcm
  Interface_USB.lib
Labels: Addition

#2608 Added IPP060N06N N-ch Mosfet
  Transistor_FET.dcm
  Transistor_FET.lib
Labels: Addition

#2395 Audio: Add CS4272 Codec
  Audio.dcm
  Audio.lib
Labels: Addition

#2117 Added STM8S208RB
  MCU_ST_STM8.dcm
  MCU_ST_STM8.lib
Labels: Addition

#2605 Add Driver_FET/ITS724G and aliases
  Driver_FET.dcm
  Driver_FET.lib
Labels: Addition

#2166 Add RTL8211EG-VB-CG
  Interface_Ethernet.dcm
  Interface_Ethernet.lib
Labels: Addition

#2610 Added STM8S208CB with aliases
  MCU_ST_STM8.dcm
  MCU_ST_STM8.lib
Labels: Addition

#2594 Added FE1.1s 4 Port USB Hub Controller
  Interface_USB.dcm
  Interface_USB.lib
Labels: Addition

#2022 Add WE-TVS-82400102 TVS Diode
  Power_Protection.dcm
  Power_Protection.lib
Labels: Addition

#2278 Added NUF4401MN.
  Power_Protection.dcm
  Power_Protection.lib
Labels: Addition

#1787 symbol: ACPL-336J
  Driver_FET.dcm
  Driver_FET.lib
Labels: Addition

#1973 Added SM712 and SD-C series TVS diodes
  Diode.dcm
  Diode.lib
Labels: Addition

#2255 Add AD5272/4
  Potentiometer_Digital.dcm
  Potentiometer_Digital.lib
Labels: Addition

#2262 Add ADP5091/ADP5092
  Battery_Management.dcm
  Battery_Management.lib
Labels: Addition

#2583 Add BT series Triacs
  Triac_Thyristor.dcm
  Triac_Thyristor.lib
Labels: Addition

#2394 add LT3093/LT3094 negative adjustable voltage regulator in MSOP-12
  Regulator_Linear.dcm
  Regulator_Linear.lib
Labels: Addition

#2577 Added LTC4314 I2C Mutiplexer
  Interface_Expansion.dcm
  Interface_Expansion.lib
Labels: Addition, Pending changes

#2616 Added YM2149F sound generation chip
  Audio.dcm
  Audio.lib
Labels: Addition

#2096 Add MAX1968 / MAX 1969 TEC drivers
  Driver_TEC.dcm
  Driver_TEC.lib
  sym-lib-table
Labels: Addition

#2538 Add alternate part numbers for STM Nucleo 144 Development boards
  MCU_Module.dcm
  MCU_Module.lib
Labels: Addition

#2087 add HCPL-0201 opto-coupler (and variants)
  Isolator.dcm
  Isolator.lib
Labels: Addition

#2410 Amplifier_Operational: Add alias of LM2904 - MCP6022
  Amplifier_Operational.dcm
  Amplifier_Operational.lib
Labels: Addition

#2581 Added DMG1012T N-Channel enhancement MOSFET
  Transistor_FET.dcm
  Transistor_FET.lib
Labels: Addition

#2393 add Hamamatsu S597x photodiode in TO-18 THT
  Sensor_Optical.dcm
  Sensor_Optical.lib
Labels: Addition

#2611 Added VIPer26LN with alias
  Regulator_Switching.dcm
  Regulator_Switching.lib
Labels: Addition

#1972 Add AX5043 tranceiver
  RF.dcm
  RF.lib
Labels: Addition

#2313 Filter: Add 1FP45-0R - EMI filter
  Filter.dcm
  Filter.lib
Labels: Addition

#2586 Add split version of G5V-2 relay symbol
  Relay.dcm
  Relay.lib
Labels: Addition

#2585 Added FODM214 and FODM217
  Isolator.dcm
  Isolator.lib
Labels: Addition

#2589 Add analog switch TS5A23159
  Analog_Switch.dcm
  Analog_Switch.lib
Labels: Addition

#2370 add NCV8402xSTT1G
  Driver_FET.dcm
  Driver_FET.lib
Labels: Addition

#2275 Added EFM32HG108F32 and EFM32HG108F64.
  MCU_SiliconLabs.dcm
  MCU_SiliconLabs.lib
Labels: Addition

#2614 Added BQ24166RGE and BQ24167RGE battery chargers.
  Battery_Management.dcm
  Battery_Management.lib
Labels: Addition

#2442 Add PCA9555
  Interface_Expansion.dcm
  Interface_Expansion.lib
Labels: Addition, Pending changes

#2603 Add Reference_Current/PSSI2021SAY
  Reference_Current.dcm
  Reference_Current.lib
Labels: Addition

#1968 Added ADM2481, ADM2483 isolated RS485 transceivers
  Interface_UART.dcm
  Interface_UART.lib
Labels: Addition

#2075 Add MAX7221
  Driver_LED.dcm
  Driver_LED.lib
Labels: Addition

#1998 Add Finder 36.11 10A SPDT relay symbol
  Relay.dcm
  Relay.lib
Labels: Addition

#1979 Add Murata MEE DC/DC converters
  Converter_DCDC.dcm
  Converter_DCDC.lib
Labels: Addition

#1978 Add 8P8C_LED_Shielded_x2
  Connector.dcm
  Connector.lib
Labels: Addition

#2148 Add W9812G6KH SDRAM
  Memory_RAM.dcm
  Memory_RAM.lib
Labels: Addition

#2546 Add ESP32-S2-WROVER SoC Module
  RF_Module.dcm
  RF_Module.lib
Labels: Addition

#2211 Add Nexperia PMEG*E[HJT] {SOD-[13]23F,SOT-23} Schottky diodes
  Diode.dcm
  Diode.lib
Labels: Addition

#2624 Add DS1882 audio log volume digital potentiometer with i2c.
  Potentiometer_Digital.dcm
  Potentiometer_Digital.lib
Labels: Addition

#2237 Fix PMEG6010 Schottky diode FPs
  Diode.dcm
  Diode.lib
Labels: Bug, Enhancement

#2390 Adding the C8051F380/1/2/3/4/5/6/7/C family (QFN32)
  MCU_SiliconLabs.dcm
  MCU_SiliconLabs.lib
Labels: Addition

#2587 Add NXP MCU MKV11Z128VLF7
  MCU_NXP_Kinetis.dcm
  MCU_NXP_Kinetis.lib
Labels: Addition

#2588 Add NXP MCU MKE16Z64VLF4
  MCU_NXP_Kinetis.dcm
  MCU_NXP_Kinetis.lib
Labels: Addition

#2388 Adding the C8051F380/1/2/3/4/5/6/7/C family (LQFP32)
  MCU_SiliconLabs.dcm
  MCU_SiliconLabs.lib
Labels: Addition

#2625 Break out LM317_3PinPackage into unique symbols
  Regulator_Linear.dcm
  Regulator_Linear.lib
Labels: Enhancement

#1942 Add Infineon Merus audio amplifier symbols
  Amplifier_Audio.dcm
  Amplifier_Audio.lib
Labels: Addition

#2557 Added Omron G2RL relay symbol with aliases
  Relay.dcm
  Relay.lib
Labels: Addition

#2389 Adding the C8051F380/1/2/3/4/5/6/7/C family (TQFP48)
  MCU_SiliconLabs.dcm
  MCU_SiliconLabs.lib
Labels: Addition

#2618 SGTL5000XNAA3 Symbol
  Audio.dcm
  Audio.lib
Labels: Addition

#899 Add symbol R_POT_MountingPin.
  Device.dcm
  Device.lib
Labels: Addition

#2236 add STUSB4500 USB PD controller
  Interface_USB.dcm
  Interface_USB.lib
Labels: Addition

#1994 add Mini-Circuits PHA-13HLN as alias
  RF_Amplifier.dcm
  RF_Amplifier.lib
Labels: Addition

#2056 add Mini-Circuits TCP-2-10X power splitter
  RF.dcm
  RF.lib
Labels: Addition

#1991 add MAX5717 and MAX5719 DACs
  Analog_DAC.dcm
  Analog_DAC.lib
Labels: Addition

#2045 add IFX27001 linear voltage regulators
  Regulator_Linear.dcm
  Regulator_Linear.lib
Labels: Addition

#2645 Fix 1N4003 description.
  Diode.dcm
Labels: Bug

#2468 Add LP3869x linear regulators
  Regulator_Linear.dcm
  Regulator_Linear.lib
Labels: Addition

#2510 Add SC16IS752
  Interface_UART.dcm
  Interface_UART.lib
Labels: Addition, Pending changes

#2647 Added Microchip PIC18F2xK22 I/P microcontrollers.
  MCU_Microchip_PIC18.dcm
  MCU_Microchip_PIC18.lib
Labels: Addition

#2642 added NCS21X Alias
  Amplifier_Current.dcm
  Amplifier_Current.lib
Labels: Addition

#2652 Added Diodes Inc AP2161W and AP2171W current limited switches
  Power_Management.dcm
  Power_Management.lib
Labels: Addition

#2654 Fix 74LS139
  74xx.dcm
  74xx_IEEE.dcm
  74xx_IEEE.lib
Labels: Bug

#1992 add DAC1220E 20-bit DAC
  Analog_DAC.dcm
  Analog_DAC.lib
Labels: Addition, Pending changes

#2598 USBLC6 ESD protection diodes
  Power_Protection.dcm
  Power_Protection.lib
Labels: Addition

#2663 Fix for LM4040 TO-92, pin 3 (NC) was used as anode (instead of pin 1)
  Reference_Voltage.lib
Labels: Bug

#2664 Revert "Fix for LM4040 TO-92, pin 3 (NC) was used as anode (instead of pin 1)"
  Reference_Voltage.lib
Labels: Bug

#2666 Fix datasheet of SIM7020x
  RF_GSM.dcm
Labels: Bug

#2661 hmc431: NC pins should be tied to ground
  RF.lib
Labels: Enhancement

#2629 MCU Module: Add NC pins on existing VisionSOM
  MCU_Module.lib
Labels: Enhancement, Pending reviewer

#2653 Add PCAL6416APW I2C port expander
  Interface_Expansion.dcm
  Interface_Expansion.lib
Labels: Addition

#2467 Clean up Comparator lib
  Comparator.dcm
  Comparator.lib
Labels: Bug, Enhancement

#2620 Added AudioPlugs
  Connector.dcm
  Connector.lib
Labels: Addition

#2354 Addition of LM5118 Buck Boost Controller
  Regulator_Switching.dcm
  Regulator_Switching.lib
Labels: Addition

#2430 Added MCP65R4x comparators
  Comparator.dcm
  Comparator.lib
Labels: Addition

#2172 Add several JFETs
  Transistor_FET.dcm
  Transistor_FET.lib
Labels: Addition

#2416 Add 8-pin Dual PMOS
  Device.dcm
  Device.lib
Labels: Addition

#2665 Add split '240 and '244 symbols
  74xx.dcm
  74xx.lib
Labels: Addition

#2517 Connector: Add a barrel jack connector symbol with reordered pins
  Connector.dcm
  Connector.lib
Labels: Addition

#2667 Add split resistor network symbols
  Device.dcm
  Device.lib
Labels: Addition

#2671 Fix LTC6754
  Comparator.dcm
  Comparator.lib
Labels: Bug, Enhancement

#2575 add LinkSwitch-TN2 family devices
  Regulator_Switching.dcm
  Regulator_Switching.lib
Labels: Addition

#2673 US1A - US2MA diodes
  Diode.dcm
  Diode.lib
Labels: Addition, Bug

#2251 Explode sodimm 200
  Connector.dcm
  Connector.lib
Labels: Addition

#2456 Add 62256 based on the existing 628128
  Memory_RAM.dcm
  Memory_RAM.lib
Labels: Addition

#2362 Addition of MLX90314 & MLX90320 Programmable Sensor Interfaces (Signal …
  Analog.dcm
  Analog.lib
Labels: Addition

#2678 Add LTC3639 (Alias of LTC3638)
  Regulator_Switching.dcm
  Regulator_Switching.lib
Labels: Addition

#2681 Add Alias for INA1x9
  Amplifier_Current.dcm
  Amplifier_Current.lib
Labels: Addition

#2675 Added DMC3071LVT as an alias of DMC2053UVT
  Transistor_FET.dcm
  Transistor_FET.lib
Labels: Addition

#2659 fix symbol to match footprint pr
  RF.dcm
  RF.lib
Labels: Enhancement

#2081 Add Conn_ST_STDC14 (STM32 debug connector, compatible with ARM debug conn.)
  Connector.dcm
  Connector.lib
Labels: Addition

#2677 Stack output and GND pins of TB6612
  Driver_Motor.lib
Labels: Bug

#2422 Added symbol for the L293E quad push-pull DC motor driver with extern…
  Driver_Motor.dcm
  Driver_Motor.lib
Labels: Addition

#2679 Add NB3N502 symbol
  Oscillator.dcm
  Oscillator.lib
Labels: Addition

#2503 Add MUN12AD01-SH and MUN12AD03-SH Switching DC/DC regulator symbol
  Regulator_Switching.dcm
  Regulator_Switching.lib
Labels: Addition

#2128 Adding ADuM1400, ADuM1401 and ADuM1402
  Isolator.dcm
  Isolator.lib
Labels: Addition
