Repository KiCad/kicad-symbols, pull requests merged in 2020-07, with the labels that each got.

#2820 Added TPS7A05 Low Iq family as alias of LP5907MFX-1.2.
  Regulator_Linear.dcm
  Regulator_Linear.lib
Labels: Addition

#2425 Add WIZnet W5500
  Interface_Ethernet.dcm
  Interface_Ethernet.lib
Labels: Addition

#2507 Add WM8731
  Audio.dcm
  Audio.lib
Labels: Addition

#2824 Adding alias for 74xx373
  74xx.dcm
  74xx.lib
Labels: Addition

#2068 Add Hirose MS-156C3 rf testpoint
  Connector.dcm
  Connector.lib
Labels: Addition, Pending changes

#1776 Request M2GL090T-FG484
  FPGA_Microsemi.dcm
  FPGA_Microsemi.lib
Labels: Addition

#2813 adding symbols for Gas Discharge Tubes
  Device.dcm
  Device.lib
Labels: Addition

#2749 ADG1408 SP8T analog switch, TSSOP-16
  Analog_Switch.dcm
  Analog_Switch.lib
Labels: Addition

#2818 Added FPF2006
  Power_Management.dcm
  Power_Management.lib
Labels: Addition

#2840 new ldo regulator XC6210B332MR
  Regulator_Linear.dcm
  Regulator_Linear.lib
Labels: Addition, Pending changes

#2798 Add shielded SIM card
  Connector.dcm
  Connector.lib
Labels: Addition

#2844 Added DP3T switch
  Switch.dcm
  Switch.lib
Labels: Addition

#2834 added ST LD39150 regulator
  Regulator_Linear.dcm
  Regulator_Linear.lib
Labels: Addition

#2850 Fix 8-pin mini DIN connector
  Connector.lib
Labels: Enhancement

#2833 Added MBR1020VL
  Diode.dcm
  Diode.lib
Labels: Addition

#2723 add LM2611 cuk converter
  Regulator_Switching.dcm
  Regulator_Switching.lib
Labels: Addition

#2849 Add AD9833
  Interface.dcm
  Interface.lib
Labels: Addition

#2730 Add AD637
  Analog.dcm
  Analog.lib
Labels: Addition

#2762 Add all permutations of common anode/cathode RGB LEDs
  Device.dcm
  Device.lib
Labels: Addition

#2687 Add SAM DA1 family
  MCU_Microchip_SAMD.dcm
  MCU_Microchip_SAMD.lib
Labels: Addition
